<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Amount per Month must more than Amount _78d48a</name>
   <tag></tag>
   <elementGuidId>80bee635-83df-4a70-9e3c-09a414e87b38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='maxAmountPerMonthError']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#maxAmountPerMonthError</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>35026f44-b66e-4c6e-b8b8-2ca4890fbdc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>maxAmountPerMonthError</value>
      <webElementGuid>c594eee9-57d1-4704-9b11-10a659c639ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>errorMsg hidden</value>
      <webElementGuid>d139e785-77f6-4631-af38-70e522415bd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Amount per Month must more than Amount per Transaction</value>
      <webElementGuid>da9d8bbf-44e9-44a6-b0a0-6d9443a613bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maxAmountPerMonthError&quot;)</value>
      <webElementGuid>058428c3-7180-41da-9c6b-eb89d7831399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9a0bcdbd-8691-4d09-8329-1c3b5fc4400e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formInput</value>
      <webElementGuid>207f4a68-a0f7-44c1-95fe-e92abe813788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
	                	 
	                	Amount per Month must more than Amount per Transaction
	                </value>
      <webElementGuid>685f8222-ef36-49fa-ac22-35955e9b4fc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;step1&quot;)/div[@id=&quot;barPadding&quot;]/div[@id=&quot;whiteMid&quot;]/div[@class=&quot;formInput&quot;]</value>
      <webElementGuid>15515a10-81ed-4570-96a9-9e5921a9f2e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='maxAmountPerMonthError']</value>
      <webElementGuid>6ce2a669-475f-41fd-b606-697492a69785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='whiteMid']/div[17]/div</value>
      <webElementGuid>1f5b4c8b-e2a1-43ca-aa54-355de2bc92bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permanent Month Limit THB'])[1]/following::div[2]</value>
      <webElementGuid>d7882602-993c-4167-8cf4-ec81723d1119</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permanent Transaction Limit THB'])[1]/following::div[6]</value>
      <webElementGuid>14982a77-e655-4f91-87b6-c69c1745c39e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks'])[2]/preceding::div[2]</value>
      <webElementGuid>6eb0d381-225e-499d-9880-a980e87fb230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div</value>
      <webElementGuid>4f1feb2b-3dde-4fca-a076-043fd4b30285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'maxAmountPerMonthError' and (text() = 'Amount per Month must more than Amount per Transaction' or . = 'Amount per Month must more than Amount per Transaction')]</value>
      <webElementGuid>8f21a261-27f6-4716-8b5e-252e895215ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='whiteMid']/div[17]</value>
      <webElementGuid>01599488-ee00-45be-9571-019c15e57ee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permanent Month Limit THB'])[1]/following::div[1]</value>
      <webElementGuid>af49a921-258a-4f5b-92df-4f8f0d72f7e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter valid Amount'])[1]/following::div[3]</value>
      <webElementGuid>6691762d-7982-4881-a342-30bc4ae06875</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks'])[2]/preceding::div[3]</value>
      <webElementGuid>a3409095-53a1-478d-b0d7-06b9db89f463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]</value>
      <webElementGuid>e6c1db69-5e4e-4b81-8060-5baa017e85b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
	                	 
	                	Amount per Month must more than Amount per Transaction
	                ' or . = '
	                	 
	                	Amount per Month must more than Amount per Transaction
	                ')]</value>
      <webElementGuid>55c49e53-ffe1-4623-9f5b-056876cdd0ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
