<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Permanent Limit Per MonthTHB_maxAmoun_ec8cd4</name>
   <tag></tag>
   <elementGuidId>e6900244-a613-496d-aa6c-8d0e3b6c6768</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#maxAmountEDCPerMonth</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='maxAmountEDCPerMonth']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>91125c38-6aa8-4463-bb18-03af9c99aa81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>maxAmountEDCPerMonth</value>
      <webElementGuid>789c4bbd-cd9c-4ccd-8b9b-a701f31cd39d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>maxAmountEDCPerMonth</value>
      <webElementGuid>4b40f244-5e27-4eac-bbde-695cea9c61a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>aeb78c79-9d41-4ddf-8833-8693727896d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>ff642030-2fdb-43e5-b18f-c625d4fc76b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>720eab7d-93b8-488b-a637-bf190100a011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maxAmountEDCPerMonth&quot;)</value>
      <webElementGuid>581e5cfc-da72-45d2-8746-76d38a1d7665</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='maxAmountEDCPerMonth']</value>
      <webElementGuid>0af7f4c8-032b-462b-81a0-bc7bfeb18883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group']/div[2]/div[26]/input</value>
      <webElementGuid>db178da5-161d-4eb8-a990-3f382b7f790b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[26]/input</value>
      <webElementGuid>290313bc-6739-4f98-b0bc-a0968688d969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'maxAmountEDCPerMonth' and @name = 'maxAmountEDCPerMonth' and @type = 'text']</value>
      <webElementGuid>57be1903-1105-483a-8ef4-e8f7e3ac14d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
