<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Permanent Limit Per MonthTHB_maxAmoun_ec8cd4</name>
   <tag></tag>
   <elementGuidId>e6900244-a613-496d-aa6c-8d0e3b6c6768</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#maxAmountEDCPerMonth</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='maxAmountEDCPerMonth']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>64d89df1-f611-4265-aee9-ee5fc62d9ee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>maxAmountEDCPerMonth</value>
      <webElementGuid>f7f511a8-aef2-4248-9f2c-6505f7f077e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>maxAmountEDCPerMonth</value>
      <webElementGuid>6fa42e9e-d15a-45e3-9314-ca56c4b35a3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>705d9a81-ca1d-42e7-84fc-ae9fa7d00392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>8f80f77e-9263-460f-993d-ee5639300ed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>720eab7d-93b8-488b-a637-bf190100a011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maxAmountEDCPerMonth&quot;)</value>
      <webElementGuid>8ca1fcc8-1319-404c-b7d0-12727c42b214</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='maxAmountEDCPerMonth']</value>
      <webElementGuid>c38c3021-6801-4a75-b9a7-8dad9b7fd648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group']/div[2]/div[26]/input</value>
      <webElementGuid>0a0ba5ea-8fae-453e-8fbd-180f64cbb5b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[26]/input</value>
      <webElementGuid>bed6f6a5-de7b-4e77-8ff6-012a67f4e1e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'maxAmountEDCPerMonth' and @name = 'maxAmountEDCPerMonth' and @type = 'text']</value>
      <webElementGuid>2c560aa4-b618-4f04-9fcf-ce4760c9b2de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
