<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Amount per Month must more than Amount_46b8eb</name>
   <tag></tag>
   <elementGuidId>29ee7ae4-e0e4-4d04-87e1-0a7617b95577</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#maxAmountEDCPerMonthError > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='maxAmountEDCPerMonthError']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0bb5a6f6-4518-4895-b19c-238bd06158da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Amount per Month must more than Amount per Transaction</value>
      <webElementGuid>e6aac57d-f129-480f-8519-f1796e582a1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maxAmountEDCPerMonthError&quot;)/span[1]</value>
      <webElementGuid>b2d0c512-7aa5-48b7-8736-5d13ba15f271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>de61d5ae-26b6-4240-b276-797fa49b1a04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Amount per Month must more than Amount per Transaction</value>
      <webElementGuid>425a3b42-35a6-4c52-ace9-0beb793ce52a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maxAmountPerMonthError&quot;)/span[1]</value>
      <webElementGuid>76f06297-397c-4436-952e-09781f4c0301</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='maxAmountEDCPerMonthError']/span</value>
      <webElementGuid>08c7a849-5af7-455d-9f01-2e2e282529c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::span[1]</value>
      <webElementGuid>1e0fadbe-93a6-44c1-8fe5-208b51a7969e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MID'])[1]/preceding::span[1]</value>
      <webElementGuid>0b8fda82-d200-4d8d-a218-745889068c6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Amount per Month must more than Amount per Transaction']/parent::*</value>
      <webElementGuid>8a2ab319-42f9-4549-898e-10e4b9ea4b0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[26]/div/span</value>
      <webElementGuid>d7c87582-0fe1-4191-b7a0-822b40a24c9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Amount per Month must more than Amount per Transaction' or . = 'Amount per Month must more than Amount per Transaction')]</value>
      <webElementGuid>20336784-b45f-42f2-9786-e92671fe8eff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='maxAmountPerMonthError']/span</value>
      <webElementGuid>b52f76dc-23c4-48fd-ab42-13d4a6459338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permanent Month Limit THB'])[1]/following::span[1]</value>
      <webElementGuid>5e70ce79-a6e0-490e-8ea2-fdde6c7b6052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permanent Transaction Limit THB'])[1]/following::span[2]</value>
      <webElementGuid>336243f8-a4d8-4dd9-a307-5097dc2d3bd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks'])[2]/preceding::span[1]</value>
      <webElementGuid>cf231be8-586a-4098-aedc-c66a29c3c639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Automate'])[2]/preceding::span[1]</value>
      <webElementGuid>bb292570-cc2e-4608-8583-1531b1c68477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div/span</value>
      <webElementGuid>5de32c63-602a-4c2b-bdda-7b92bd42c396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter valid Amount'])[1]/following::span[1]</value>
      <webElementGuid>2bbf93bc-92e3-477f-ab78-d5996caf1121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Optional)'])[1]/preceding::span[1]</value>
      <webElementGuid>e1f73e34-2ebd-4a2e-a7c7-2b38113332b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
