<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search_search</name>
   <tag></tag>
   <elementGuidId>64841d65-e89a-45ac-8604-8514d1bfa7f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>95737a75-6168-4764-8bc2-34ef64740773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5a3bde7d-60af-414e-b549-893c14ab54f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>b82a9a80-3b3e-41b6-a467-313ea6dde266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>02fc4d93-e387-4fe9-8cfc-51caf57d74bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search txt18 white</value>
      <webElementGuid>7d32d7bd-5090-4ab5-b700-2e0c38c98d93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Batch No.</value>
      <webElementGuid>e9c67e4c-dd7d-4dc8-965e-ecfb2cfcedd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>clickclear(this, 'Batch No.')</value>
      <webElementGuid>9177bdd2-8c9f-49d2-8fed-bb767a5a0083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>clickrecall(this,'Batch No.')</value>
      <webElementGuid>ccce7985-1081-452a-94d5-61c3c8e22480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6fcb0ebb-f3d4-41f1-b965-2fc4853a7e81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search&quot;)</value>
      <webElementGuid>1f65e3c3-a3a6-4cb0-a7e0-f50cd008a70c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='search']</value>
      <webElementGuid>35ede28d-f468-41ac-8b81-f7dbb57c7c1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='beigeMid']/form/div[2]/input</value>
      <webElementGuid>e65ebb40-6be1-428b-909f-f0e6e89923d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>21cce0e3-1a4f-4acd-9e97-d96007eabbbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'search' and @name = 'search']</value>
      <webElementGuid>adf52ed0-f612-4ef5-8dee-386440685006</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
