<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_SUCCESS</name>
   <tag></tag>
   <elementGuidId>f36d2213-886c-497d-9215-01997d8d647b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='detailBox']/div[17]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d83a5912-cfb6-44b0-bc6a-45306e38269a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>allDoneValue wrapped</value>
      <webElementGuid>fe84bf47-7869-42c0-a1cf-e721d4938a68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SUCCESS.</value>
      <webElementGuid>e026fecb-1414-4371-913f-4189bf488ab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;detailBox&quot;)/div[@class=&quot;allDoneValue wrapped&quot;]</value>
      <webElementGuid>4465532c-9b21-4003-a4cb-fd8ff361d7fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='detailBox']/div[17]</value>
      <webElementGuid>2cbbffdd-adc9-4890-85e5-1e73ad7c9324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Response Description'])[1]/following::div[1]</value>
      <webElementGuid>0a4f50fd-7794-4af2-be3e-32e4070ce6ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Response Code'])[1]/following::div[4]</value>
      <webElementGuid>6b91461f-5459-4686-a2e1-12f44e1bae3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Print'])[1]/preceding::div[4]</value>
      <webElementGuid>7a9d14a0-ba0f-4f9d-a5ba-011ea2b6b060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email (PDF)'])[1]/preceding::div[4]</value>
      <webElementGuid>e26db210-67bb-4bb7-be5a-6bf92d097d3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SUCCESS.']/parent::*</value>
      <webElementGuid>5e1a0b4b-dec5-4c4e-bae6-dfc0c7608c58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]</value>
      <webElementGuid>08fb3eb1-2dea-4499-8adc-7253dd014379</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'SUCCESS.' or . = 'SUCCESS.')]</value>
      <webElementGuid>ed8ebb63-cdc2-4b08-afac-1cc168567bf2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
