<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_201020112012201320142015201620172018_c54268</name>
   <tag></tag>
   <elementGuidId>bb5462f3-18d5-446a-8f81-957dd7db076c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select.ui-datepicker-year</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//select[@onclick=&quot;DP_jQuery_1679985377493.datepicker._clickMonthYear('#fromdate');&quot;])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f2ec5273-ab3f-43b9-9cb6-a7c7433cce3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-datepicker-year</value>
      <webElementGuid>c1481ea9-2ea3-43e0-a320-04667e3e7abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>DP_jQuery_1679985377493.datepicker._selectMonthYear('#fromdate', this, 'Y');</value>
      <webElementGuid>fb98ecfd-2619-49ef-8acc-bf6b4a508119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>DP_jQuery_1679985377493.datepicker._clickMonthYear('#fromdate');</value>
      <webElementGuid>67a3538d-7eac-43d8-a601-ea32eb2d92be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>202f77fb-2a97-45ac-98d9-665b43932ead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2010201120122013201420152016201720182019202020212022</value>
      <webElementGuid>47d8c4a8-1f8c-49a4-ac75-3a9799b7b8ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-datepicker-div&quot;)/div[@class=&quot;ui-datepicker-header ui-widget-header ui-helper-clearfix ui-corner-all&quot;]/div[@class=&quot;ui-datepicker-title&quot;]/select[@class=&quot;ui-datepicker-year&quot;]</value>
      <webElementGuid>20475cb6-ec92-4e64-894d-435b1a188527</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//select[@onclick=&quot;DP_jQuery_1679985377493.datepicker._clickMonthYear('#fromdate');&quot;])[2]</value>
      <webElementGuid>c7440e48-9b2e-4eb0-aa0b-cb4aa94f9cd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-datepicker-div']/div/div/select[2]</value>
      <webElementGuid>84f3820b-046a-48ba-9bba-4c949a0176aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::select[2]</value>
      <webElementGuid>b177aa78-2ae1-4a43-8af1-0dec722dcc90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prev'])[1]/following::select[2]</value>
      <webElementGuid>79d36282-7d79-4469-92b9-8d107f09b007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Su'])[1]/preceding::select[1]</value>
      <webElementGuid>f4eb2e76-bf43-4fbf-818e-3b50ffeb4118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mo'])[1]/preceding::select[1]</value>
      <webElementGuid>def7fd68-4ad3-4fd3-8c26-a58dedcfc004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[2]</value>
      <webElementGuid>b89e8047-7b04-479c-9af9-9c3006f8698f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = '2010201120122013201420152016201720182019202020212022' or . = '2010201120122013201420152016201720182019202020212022')]</value>
      <webElementGuid>3ab6caee-7587-4847-855c-d8a2ce8d9f2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
