<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add Merchant ID</name>
   <tag></tag>
   <elementGuidId>6996df8b-33e8-49eb-8278-5e88fd3545e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addMidEDC</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='addMidEDC']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bac82e63-fde7-4eb1-9cd2-7d161ff582cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button btnWidth_180</value>
      <webElementGuid>aa81b592-d772-4bb7-aa71-9f6fa88479c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>7e6fbe0a-a505-4e02-a84b-6db1d72a892d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addMidEDC</value>
      <webElementGuid>8f6a3f9d-1f47-4721-8adb-1dd2b45c94a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Merchant ID</value>
      <webElementGuid>78e3e65d-e3df-42b1-9472-9e67a8a5395e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addMidEDC&quot;)</value>
      <webElementGuid>853383a2-ccae-42c4-a402-8406009f86e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='addMidEDC']</value>
      <webElementGuid>7e5fc5db-6d41-4196-a66d-304b6151a6b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='groupEDC']/div[2]/div[17]/a</value>
      <webElementGuid>7c1d1588-8ab2-4a4c-9aa5-f95b37fa7616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Add Merchant ID')]</value>
      <webElementGuid>7544204a-bd66-417a-9c44-6d6b6ea54ae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Postcode'])[2]/following::a[1]</value>
      <webElementGuid>beae02d4-5144-42c4-bafc-f283d5aa5aad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bangkok'])[3]/following::a[1]</value>
      <webElementGuid>079c95be-b787-459e-a89f-b875e494c829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::a[1]</value>
      <webElementGuid>03a95386-3b25-4484-ad32-e4d3f81db07d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company Name'])[2]/preceding::a[2]</value>
      <webElementGuid>2fd2c796-1241-43b0-83aa-c485cbff9114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0)')]</value>
      <webElementGuid>c1da2aea-00a2-4a01-bba3-b9e7438d9487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/a</value>
      <webElementGuid>c90ca26f-7205-4fc9-ac24-63b76d6a5aff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and @id = 'addMidEDC' and (text() = 'Add Merchant ID' or . = 'Add Merchant ID')]</value>
      <webElementGuid>76e7d9b0-334c-4ed6-9466-e28990a09567</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
