<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Merchant ID (MID)_formInputS</name>
   <tag></tag>
   <elementGuidId>17fce772-d2d1-4730-be64-6b8b9b1d717d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.formInputS</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='groupEDC']/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>db0535f0-a431-47d9-a317-fd1ad664c488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formInputS</value>
      <webElementGuid>8db1c683-95d8-4b95-9bdd-5407c5e5d3e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;groupEDC&quot;)/div[@class=&quot;TableBorder&quot;]/div[@class=&quot;formInputS&quot;]</value>
      <webElementGuid>b5d0ae14-9aeb-4031-b517-c056006fb115</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='groupEDC']/div[2]/div[2]</value>
      <webElementGuid>2c82bd43-5cc5-4ba6-833d-9b4fd880ec28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Merchant ID (MID):'])[1]/following::div[1]</value>
      <webElementGuid>bfcb05e6-c80f-4cab-8007-dc8a91a8d23a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Merchant ID'])[1]/following::div[3]</value>
      <webElementGuid>591c95b2-4f3f-4596-91f5-e4b526194617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Merchant Name:'])[1]/preceding::div[3]</value>
      <webElementGuid>7fe80a08-8017-4e0a-b1fe-c1d7dec16750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div[2]</value>
      <webElementGuid>e3c8b020-d174-4685-892d-3e72c3aec3a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
