<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Business Contact No_businessContact</name>
   <tag></tag>
   <elementGuidId>ff98d25e-51e1-46a4-ab63-22323f0b6cf7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#businessContact</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='businessContact']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c2dfd70a-cbd4-42a8-88c5-1b58a2c6a31d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>businessContact</value>
      <webElementGuid>4b72db28-a891-4357-b498-25d236a0f752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>businessContact</value>
      <webElementGuid>909dbebf-369b-4c44-bcc0-0546406efa59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3d3b1117-af62-43b6-89df-926148ce6760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>12989fc0-fa70-466c-9d03-2ba7141840aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>defaultValue</value>
      <webElementGuid>793a301a-9832-4e5e-a21a-19057faceee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>clickclear(this, '021234567')</value>
      <webElementGuid>8be4eabf-3023-4b62-9b9f-f1717504e472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>clickrecall(this, '021234567')</value>
      <webElementGuid>73c8356f-06ff-4122-8bed-386e6e7e96a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>021234567</value>
      <webElementGuid>4bc77b56-5b88-4b60-84df-ccbaf3494c3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e4fd337c-988c-4413-8ef3-005c0e8e894d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;businessContact&quot;)</value>
      <webElementGuid>7304628a-234e-40e7-b201-fa320f6d8435</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='businessContact']</value>
      <webElementGuid>50780bee-0df1-4396-9906-e835258c6853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='whiteMid']/div[29]/input</value>
      <webElementGuid>8ae5d7a3-5e6a-4fd8-af85-8f09b6a96bd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[29]/input</value>
      <webElementGuid>5365794a-a5be-4356-b909-a826119cfd7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'businessContact' and @name = 'businessContact' and @type = 'text']</value>
      <webElementGuid>ad585366-77e3-4f0f-a27c-7244e8641d8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
