<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Company Short Name_businessShortName</name>
   <tag></tag>
   <elementGuidId>4ca56558-4a93-4435-9612-27ed68769dd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#businessShortName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='businessShortName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1877956e-7514-47e7-bab3-baee3da2c68e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>businessShortName</value>
      <webElementGuid>2a4e35bc-1a97-486f-a30c-d86f53006517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>businessShortName</value>
      <webElementGuid>9f411272-4226-46f7-95fe-4393cf854cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c74c6545-0bd9-4759-be59-25322bc27ab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>a6b31d0f-0f7f-45c0-a7d2-72f699c1f1e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8e9ec960-1e80-43f4-92fc-da38f46a423e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;businessShortName&quot;)</value>
      <webElementGuid>40a00ae2-5c59-4336-9e42-cefc09df7920</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='businessShortName']</value>
      <webElementGuid>7fc79361-e39c-409a-b10d-ce8c1456874d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='whiteMid']/div[5]/input</value>
      <webElementGuid>5093663d-6f8b-4918-812b-4e7c507512a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>be53bea7-65ea-44a8-b507-b4bed1e448dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'businessShortName' and @name = 'businessShortName' and @type = 'text']</value>
      <webElementGuid>c13167fe-3dfe-4db2-9244-cb17fcf6f963</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
