<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Type of Business_businessType</name>
   <tag></tag>
   <elementGuidId>bdb3bb25-b73f-421c-aacb-b671ba4d3530</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#businessType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='businessType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>63112452-f0a3-44f4-8048-66aa428e2a73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>businessType</value>
      <webElementGuid>8d3f9106-0500-4488-877b-9cc9e73b37de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>businessType</value>
      <webElementGuid>3591e22d-6fb7-4d94-b222-e663900c7ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>16bf8581-fb45-4e75-b235-b825a9fd1e4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>8d569600-174d-4c45-a942-a2f764624fc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>809bc0af-ea9e-440a-ae6d-52e47d241a6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;businessType&quot;)</value>
      <webElementGuid>42cdcdd0-a2d2-4507-9260-96caab72b4e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='businessType']</value>
      <webElementGuid>35513b3f-4944-4bf4-aac5-9c3a62901507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='whiteMid']/div[8]/input</value>
      <webElementGuid>f4a21e25-3a95-408d-9e65-3200aa1f3244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/input</value>
      <webElementGuid>d8d0ebea-09c5-41a4-994c-b3fb5c8e88e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'businessType' and @name = 'businessType' and @type = 'text']</value>
      <webElementGuid>040bfcc7-b34b-44de-840d-eddd88604638</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
