<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Limit per MonthTHB_maxAmountEDCPerMonth</name>
   <tag></tag>
   <elementGuidId>6e46cfa2-7677-43a3-8e5f-e96c689a0729</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#maxAmountEDCPerMonth</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='maxAmountEDCPerMonth']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>781aa961-b52c-4398-ae68-e9f1a0f6cd19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>maxAmountEDCPerMonth</value>
      <webElementGuid>807d9352-541a-4386-8674-c760cea5cd2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>maxAmountEDCPerMonth</value>
      <webElementGuid>18001139-43d6-48d8-bb05-024d3ed62675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9276f3c4-ce71-4829-a4d8-e0e16db393d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>3ce85a35-a117-4228-b1fd-c4cd41c47fa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>125dd7a2-62c0-4b3e-88f8-7bfcfe75d834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maxAmountEDCPerMonth&quot;)</value>
      <webElementGuid>037254d6-6147-4012-9670-6248a8bb7f84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='maxAmountEDCPerMonth']</value>
      <webElementGuid>8068a1f1-24f1-4141-9076-bf00c2e12161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='groupEDC']/div[2]/div[11]/input</value>
      <webElementGuid>508de8e5-7445-4c74-8a09-12f05bc26363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div[11]/input</value>
      <webElementGuid>ad3b00ff-bde5-4be4-95d9-bedb2ec5a8c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'maxAmountEDCPerMonth' and @name = 'maxAmountEDCPerMonth' and @type = 'text']</value>
      <webElementGuid>022f7179-14b4-44b2-8e43-9a23abc2f7da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
