<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Merchant ID (MID)_mid</name>
   <tag></tag>
   <elementGuidId>087f0079-6c19-451d-8c8c-4fd899644f96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bea812a9-958c-4f6c-b32e-2cdba07583d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mid</value>
      <webElementGuid>b909099f-0ecb-44ed-a611-289082f5fa7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mid</value>
      <webElementGuid>840bee8b-2936-4e37-8a2a-439ba364409b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cbd99806-a726-4fe4-8197-595da66bfba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>4a02bf4d-f1a7-442a-a656-a8516a511510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0359a53c-4097-4029-97a7-71a53e0b9664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mid&quot;)</value>
      <webElementGuid>baa3293d-11a5-4807-91f4-59180613a353</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mid']</value>
      <webElementGuid>8366a4db-22d7-4eb6-8d4a-90d54156c272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='groupEDC']/div[2]/div[2]/input</value>
      <webElementGuid>e137c5c8-e97f-43ff-b9a7-ec45ed1bea28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div[2]/input</value>
      <webElementGuid>0b425fb5-1c76-4b75-8c25-f140cef36818</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mid' and @type = 'text']</value>
      <webElementGuid>d1ff4cdd-cc6e-43ba-b383-a65a8ccc00cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
