<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Merchant Name_midName</name>
   <tag></tag>
   <elementGuidId>ff1a8651-aa95-4925-b56f-93f349410638</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#midName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='midName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dd3bca33-57ec-4013-9562-222a6131587e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>midName</value>
      <webElementGuid>ca174366-86b2-4376-b081-c9bb6f06dabc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>midName</value>
      <webElementGuid>3856af98-c40e-48bc-b698-84b5da82bb29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eedbb007-ad73-414d-a6ac-328dc9f9386f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>af27e35c-4517-4776-b39b-300d9c721877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e9289e49-df9d-496f-99ff-f7ca51ae20c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;midName&quot;)</value>
      <webElementGuid>d031db43-77f3-4224-8e8c-e896b19f9d1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='midName']</value>
      <webElementGuid>a31ef7ce-d905-4495-a349-07c1db34e369</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='groupEDC']/div[2]/div[5]/input</value>
      <webElementGuid>44c80366-aae7-4d28-be1f-37fc1fae6a9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div[5]/input</value>
      <webElementGuid>08a8e69f-0e3b-4878-8b2e-389625e1e483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'midName' and @type = 'text']</value>
      <webElementGuid>49697b00-e442-4854-a3a8-5d3f0c9fa0b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
