<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Go</name>
   <tag></tag>
   <elementGuidId>55520cc2-7a89-4c38-8cb3-07c04323a205</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#go90841 > div.floatL > #buttonGo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='buttonGo'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3476d3fa-824a-4c3c-ac95-60688fd7f33f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buttonGo</value>
      <webElementGuid>5ff93ca0-fee7-4258-9243-7f720417be8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font13Bold</value>
      <webElementGuid>a647e502-7137-44fe-9394-bcc05531cf88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:document.go90841.submit();</value>
      <webElementGuid>7d965fe0-539b-4382-81cf-851f7118d52f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
				                		Go
				                	</value>
      <webElementGuid>d8ea553e-dff4-40e0-b4a1-49b07a0e3c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;go90841&quot;)/div[@class=&quot;floatL&quot;]/a[@id=&quot;buttonGo&quot;]</value>
      <webElementGuid>b976d4f8-dba5-48f0-aafc-3d9d87c2412a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id='buttonGo'])[2]</value>
      <webElementGuid>3ef77a30-7c20-4394-85cc-e13c94d8354b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='go90841']/div[2]/a</value>
      <webElementGuid>f2a8d933-42eb-4be2-b233-c289e045631e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Go')])[2]</value>
      <webElementGuid>0c8ccda3-99c3-4658-be5a-08a50ef2cd5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Details'])[3]/following::a[1]</value>
      <webElementGuid>cd4b983a-5c5e-42fc-abc1-ae3cab7dcabd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Staff Admin'])[3]/preceding::a[1]</value>
      <webElementGuid>c889c45e-594a-4f23-af98-1197e658cd1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:document.go90841.submit();')]</value>
      <webElementGuid>29b31f80-c931-49ba-804e-bbe990df356a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[6]/form/div[2]/a</value>
      <webElementGuid>5b741948-d88e-4ab5-b559-1e45533e220f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'buttonGo' and @href = 'javascript:document.go90841.submit();' and (text() = '
				                		Go
				                	' or . = '
				                		Go
				                	')]</value>
      <webElementGuid>4bdd6add-e89b-46d3-97f1-8cfb486b7bcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='buttonGo']</value>
      <webElementGuid>f71d6cc9-7690-48d9-a9bc-0b1f7b13048d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Go')]</value>
      <webElementGuid>6b5343c5-7c23-494b-b4bb-b4d089dbf604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Details'])[2]/following::a[1]</value>
      <webElementGuid>ca45f67c-3f4c-4c33-b7c2-8eb5aeb5765f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Digio'])[2]/preceding::a[1]</value>
      <webElementGuid>92eda1a3-e52f-4487-b756-93a8f5a5fddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Go']/parent::*</value>
      <webElementGuid>92d318c1-92b3-4797-b7b9-c5bd8e2c1c04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/a</value>
      <webElementGuid>33c3b45c-6f86-4d88-bcfa-10d7993341ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
