<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contact No_contact</name>
   <tag></tag>
   <elementGuidId>e3f192cb-305b-45ac-b4fc-4b7537b17412</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#contact</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='contact']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>14365e63-0a52-4f49-8fca-411d36adea16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contact</value>
      <webElementGuid>d146df99-fcb5-4cf8-a7d3-281baeee4d2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>contact</value>
      <webElementGuid>c19e38f8-6cac-433c-b9a2-45a2af76584f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>117f130e-39c6-4a11-939a-1411139043e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>4565355d-9d5a-4676-8590-55389e62381d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>defaultValue</value>
      <webElementGuid>5aa7b770-424b-4455-a22b-afa815fec274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>clickclear(this, '08X1234567')</value>
      <webElementGuid>3e34d8e4-5233-4f40-b1c1-afc9fe71dd74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>clickrecall(this, '08X1234567')</value>
      <webElementGuid>5ae9a4a8-e95e-4a1a-bfbc-acfbe4058bd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>08X1234567</value>
      <webElementGuid>8c2655d0-089a-42e1-a6de-645bb1b8b5c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contact&quot;)</value>
      <webElementGuid>30fa8efb-501d-4d22-914e-d33a76b29947</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='contact']</value>
      <webElementGuid>cc68fcc4-7b3f-46b6-8b8b-e1a8601d5bd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='whiteMid']/div[4]/input</value>
      <webElementGuid>b610208c-a91a-4546-8ba3-f9eb34b318a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>29d2a26d-5e32-4edb-a275-88caa57e8406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'contact' and @name = 'contact' and @type = 'text']</value>
      <webElementGuid>413a400a-5fc1-4ec8-97f7-497fcaa34ac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='whiteMid']/div[7]/input</value>
      <webElementGuid>6a9935b0-cfc7-414d-bf30-fc18300f4fe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/input</value>
      <webElementGuid>4f7d877c-15db-4a35-abc1-df0eb715a513</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
