<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Submit</name>
   <tag></tag>
   <elementGuidId>5d93b2e2-2b6d-4a8a-a660-111abf67b68a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctaMid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctaMid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>059810cd-ef2d-4347-8fa2-a5a4abd525c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctaMid</value>
      <webElementGuid>26e3b577-1210-4255-a556-25b2a0cc6e57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
				   		Submit
						
					</value>
      <webElementGuid>93ae8f1b-d9b3-4918-b372-48e2bf372e4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;step1&quot;)/div[@id=&quot;barPadding&quot;]/div[@id=&quot;ctaMid&quot;]</value>
      <webElementGuid>8e358553-2ae9-4b02-91d0-0e02163bcabd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ctaMid']</value>
      <webElementGuid>9ea4d4af-2f65-44a7-8fb4-78fea56866af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='barPadding']/div[4]</value>
      <webElementGuid>5b2dd0bd-65ef-4782-9c08-2d7baa42d93d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter valid Email'])[1]/following::div[3]</value>
      <webElementGuid>86805ffb-b032-4143-9478-e6612baa8e58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Address'])[1]/following::div[5]</value>
      <webElementGuid>6ea6538e-30ef-4120-a7b0-6dfa2d84ad3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User ID'])[2]/preceding::div[4]</value>
      <webElementGuid>ab742fe7-7e05-4628-a090-9adcc1967a1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[4]</value>
      <webElementGuid>3e924ce4-d406-4629-a5f8-120b3ecae4c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ctaMid' and (text() = '
				   		Submit
						
					' or . = '
				   		Submit
						
					')]</value>
      <webElementGuid>31d79cb2-f23e-47fb-be28-3b749ab92a07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
