<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Suspend Authorizer Reason 1_description</name>
   <tag></tag>
   <elementGuidId>949be0fa-f49c-4f4f-ad4d-4bba4b63b61a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#description</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='description']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>925a7004-8f52-41b7-b362-82f660f721bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>description</value>
      <webElementGuid>d75c9233-2c48-4012-9206-495718245d0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>description</value>
      <webElementGuid>46268c1e-9636-4278-a9b3-14f3ace3cd46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>6578a46e-086c-4deb-a397-0b1c08790e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>limitText(this.form.description,this.form.countdown,250);</value>
      <webElementGuid>e63323e8-0bf2-4faa-9499-af911bab1268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>limitText(this.form.description,this.form.countdown,250);</value>
      <webElementGuid>9878c1c2-0993-4ef0-bbab-ccda4435f3a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1bf9924e-2cd2-4bbb-8f0f-0e40fe622d11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;description&quot;)</value>
      <webElementGuid>22b9fbbc-98c3-4f20-8cbc-941144bd6c02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='description']</value>
      <webElementGuid>b4297830-283d-4a87-a97b-f0e6baccc3f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='whiteMid']/div[9]/textarea</value>
      <webElementGuid>439f12d1-4e65-45dd-9b5c-8f9a1e19b1c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>a91c8d7f-946a-44e5-ac24-6506d455cf27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'description' and @name = 'description']</value>
      <webElementGuid>eed2f3e8-4c51-444e-ac53-4748550761ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='whiteMid']/div[6]/textarea</value>
      <webElementGuid>46c84ff3-2624-4a9e-b837-2393277eb740</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
