<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select</name>
   <tag></tag>
   <elementGuidId>5a21bd3e-7414-45fa-b7aa-75a68051f7b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modalClose</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modalClose']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ba962f82-9cee-4925-ad3e-889fe5c4825f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modalClose</value>
      <webElementGuid>b06ffc21-3844-4574-9a81-b555a84debdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn</value>
      <webElementGuid>e588f0a6-0bc2-4083-9183-1f32be327cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>selectParent()</value>
      <webElementGuid>db0e7933-1dd3-49ad-8cd9-d110677a6f27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>2efbcd4d-217d-4b5d-9678-a99f50bdf420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchResultTable&quot;)/tbody[1]/tr[1]/td[3]/div[@id=&quot;modalClose&quot;]</value>
      <webElementGuid>1908a1d2-b4ec-4a4a-847f-652f831b8983</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='modalClose']</value>
      <webElementGuid>c7adb1ab-705f-4f31-9955-3c0c3e1f78f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='searchResultTable']/tbody/tr/td[3]/div</value>
      <webElementGuid>72eaab0b-2eaf-4047-b0f5-a437261f2121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Digio'])[1]/following::div[1]</value>
      <webElementGuid>9482624c-fab8-44aa-b7e6-a6127895132c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[1]/following::div[1]</value>
      <webElementGuid>5cca0c54-d136-4e1c-a1e5-0b9adb25dc49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Digio'])[2]/preceding::div[1]</value>
      <webElementGuid>b91d60ca-1552-405e-b512-12a24630daab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select'])[2]/preceding::div[1]</value>
      <webElementGuid>2fecae33-71da-4ebd-ba03-34a9144296f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select']/parent::*</value>
      <webElementGuid>7873da80-cd62-41e7-af03-f18bc10d5deb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div</value>
      <webElementGuid>bd173a89-ddcf-443e-b7f0-6891a6c43a19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'modalClose' and (text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>9d359c5d-aeae-4cfd-ba73-f6dd4929cc6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
