<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Company Name_companyNameModal</name>
   <tag></tag>
   <elementGuidId>2a3611b8-0a8e-4828-ad4c-bd512b3f7289</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#companyNameModal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='companyNameModal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5b71cab7-eb40-4d44-87a0-259b5808f253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>companyNameModal</value>
      <webElementGuid>6bf191b8-cb4c-4477-857d-eb1a1448c79d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>companyNameModal</value>
      <webElementGuid>7a41c840-33a8-4cb1-bc87-6193c2544533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b988a50a-8803-4b5f-a8b2-a1c54ddaf86e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1ca991d7-d3de-4abd-adb8-0bfa8fcee1ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6c6955f0-969b-419c-8acf-847e6c9ae507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;companyNameModal&quot;)</value>
      <webElementGuid>0b49a6e8-9ee3-4929-8cf2-cde6a001becb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='companyNameModal']</value>
      <webElementGuid>220b99cc-fa54-4d79-b87b-0e3e0cf32e52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='whiteMid']/div[7]/input</value>
      <webElementGuid>728221e6-dade-4fbb-8fd4-60d9ebf00240</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/input</value>
      <webElementGuid>4b24fada-87f8-4cb6-861a-e2faefe97bca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'companyNameModal' and @name = 'companyNameModal' and @type = 'text']</value>
      <webElementGuid>50f09098-3445-46c5-9313-480ddf3f9580</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
