<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_concat(Merchant, , s bank account _5b8a53</name>
   <tag></tag>
   <elementGuidId>d1a84e1f-b41c-4d27-8a5a-afb8912f3785</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='remarks']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#remarks</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>6a0a0f13-e17d-4b24-b615-ac86acc15ab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>remarks</value>
      <webElementGuid>daa3744b-7987-420f-9528-e06d8962b544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>remarks</value>
      <webElementGuid>725f9820-bbe2-4e9a-8f8f-9e709c7fd7a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>69ff5769-f35d-42a5-88ca-aa9641e5ef36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>limitText(this.form.remarks,this.form.countdown,250);</value>
      <webElementGuid>bbfe65d4-0403-43b1-a13d-8672e0819c8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>limitText(this.form.remarks,this.form.countdown,250);</value>
      <webElementGuid>fd958f81-4b5c-40d0-9f88-efffc36ae6d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ace1ce98-05e3-4819-b130-eb903e1d2367</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;remarks&quot;)</value>
      <webElementGuid>d8306ef7-e8db-40c0-833d-c5c176f71656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>9899b4d7-0318-4cb6-a3a2-1617b4904e36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>remarks</value>
      <webElementGuid>4f6a231b-8bcc-4f48-bfe0-ff9c102e4aba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>remarks</value>
      <webElementGuid>085b2d2c-1d09-4942-a170-481f80164da4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>d4af2d6c-3298-4d9b-b4c3-f6ac04ca23d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>limitText(this.form.remarks,this.form.countdown,250);</value>
      <webElementGuid>3f7fd919-add5-4590-a27c-baca069ecd23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>limitText(this.form.remarks,this.form.countdown,250);</value>
      <webElementGuid>47147835-cb43-4466-9729-b50d30f598e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>df8b4eef-5821-4c17-8576-941ea0894680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;remarks&quot;)</value>
      <webElementGuid>4cefec7c-6335-41f3-8326-f4d5340ba546</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='remarks']</value>
      <webElementGuid>55127b21-961c-403c-a6c8-2d1731f2f0ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='whiteMid']/div[7]/textarea</value>
      <webElementGuid>33099727-1c25-44ae-93f6-fd3c9434052d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>37d00b16-e578-41eb-9791-97882c4f08eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'remarks' and @name = 'remarks']</value>
      <webElementGuid>b66ae199-c072-428f-8086-779c6d870c6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
