<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ManageReaders</name>
   <tag></tag>
   <elementGuidId>bfb596aa-d7f2-43a2-81c7-c3972fdad920</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(6) > a > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='topNavi']/li[6]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6da6d2dc-ce35-4c20-b155-6fa274856711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ManageReaders</value>
      <webElementGuid>db699ea3-6288-4bf4-9583-27a17b43e706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topNavi&quot;)/li[6]/a[1]/span[1]</value>
      <webElementGuid>2514f87a-cc4d-4183-876c-988ddffc3e84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='topNavi']/li[6]/a/span</value>
      <webElementGuid>cf8c131a-7b14-4f6d-beac-6a3e7464f83d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ManageCompany Users'])[1]/following::span[1]</value>
      <webElementGuid>c6bfdc5f-1b67-4ecd-9b86-33bb389bf381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ManageStaffs'])[1]/following::span[2]</value>
      <webElementGuid>b8df29e5-9b7b-4d21-bff0-13bf360f1371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ManageTransactions'])[1]/preceding::span[1]</value>
      <webElementGuid>48f41814-6e07-4b79-ae94-629eef47bf9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ManageCredit Settlements'])[1]/preceding::span[2]</value>
      <webElementGuid>db9a9b35-2d7e-4236-b70c-2067745c3b99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a/span</value>
      <webElementGuid>34f2ec82-9082-4ef4-8489-721bb0dd3232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'ManageReaders' or . = 'ManageReaders')]</value>
      <webElementGuid>3bbb6d4d-e5fa-4d98-b161-0d976f7fe70d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
