<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Merchant Receipt (PDF)</name>
   <tag></tag>
   <elementGuidId>c3d3a28e-1e94-493a-b8a0-0856f09b5cdb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='beigeMid']/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#beigeMid > div.floatR > a.button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2372cf8f-5898-4641-a175-ebbbb9a577db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c5a73e1e-b86a-4370-9d1a-df1ae8ccad57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>getItemReceipt?itemid=4832463&amp;type=merchant</value>
      <webElementGuid>962ca5f0-8f9d-4c81-8846-260bf4e31c67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Merchant Receipt (PDF)</value>
      <webElementGuid>2bd645f8-aea2-4b1e-9137-68134548872c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rightMainContent&quot;)/div[@id=&quot;barPadding&quot;]/div[@id=&quot;beigeMid&quot;]/div[@class=&quot;floatR&quot;]/a[@class=&quot;button&quot;]</value>
      <webElementGuid>79b218c5-572f-4b5a-90e4-f2d8fefe3731</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='beigeMid']/div/a</value>
      <webElementGuid>5b35c784-79a4-4fd5-8ae6-9f55e164d815</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Merchant Receipt (PDF)')]</value>
      <webElementGuid>842f2057-b0a4-4d4a-a2ed-8ea5e79704ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cryptogram Information Data(CID)'])[1]/following::a[1]</value>
      <webElementGuid>2ec78b15-3235-4565-ad7c-3e800e0f6898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terminal Capabilities'])[1]/following::a[1]</value>
      <webElementGuid>d440bbe9-8edb-449c-8c49-a6749cc251d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Receipt (PDF)'])[1]/preceding::a[1]</value>
      <webElementGuid>08875312-c9ad-469f-8248-8ff4e106f290</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Void Receipt (PDF)'])[1]/preceding::a[2]</value>
      <webElementGuid>9eed4067-5652-4aaf-8495-50afe132260a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Merchant Receipt (PDF)']/parent::*</value>
      <webElementGuid>cb8416f1-2c71-482c-9cc9-717a3b275e36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'getItemReceipt?itemid=4832463&amp;type=merchant')]</value>
      <webElementGuid>c2ee820a-4f60-4941-b08e-dcfab7ecbdeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/a</value>
      <webElementGuid>39d2c824-1759-4666-8493-db8bb05e46bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'getItemReceipt?itemid=4832463&amp;type=merchant' and (text() = 'Merchant Receipt (PDF)' or . = 'Merchant Receipt (PDF)')]</value>
      <webElementGuid>d75a9aaa-b315-44c3-a69a-3030a84cba52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
