<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No available TID_paymentSelected</name>
   <tag></tag>
   <elementGuidId>2a015018-3f89-4204-89de-7fb2b932aa31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MidDes.checkBoxInput.width30FloatLeft > input[name=&quot;paymentSelected&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='paymentSelected'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>47b51304-deea-44ea-a5a3-5342f5bb761b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>paymentSelected</value>
      <webElementGuid>218fb432-0724-4f5d-9318-b11d38d6c0cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b7245818-7018-4d7e-b6eb-acdef6e50b40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox checkBoxInp</value>
      <webElementGuid>411978be-e7da-43c1-86b7-2c498f1b0582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>401002894510001</value>
      <webElementGuid>a24d84b4-3e0f-46c8-85d8-cf7e16317bff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3ccdded7-76a2-4e12-97a4-5b341520ceb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;step1&quot;)/div[@id=&quot;barPadding&quot;]/div[@id=&quot;whiteMid&quot;]/div[@class=&quot;PayMent paddDetailBox2&quot;]/div[@class=&quot;groupLoop&quot;]/div[@class=&quot;Midloop&quot;]/div[@class=&quot;checkBoxDiv&quot;]/div[@class=&quot;width250FloatLeft boldHeaderText font14Black&quot;]/div[@class=&quot;MidDes checkBoxInput width30FloatLeft&quot;]/input[@class=&quot;checkbox checkBoxInp&quot;]</value>
      <webElementGuid>de66bc90-0824-4dda-8e15-96d3c2e2f367</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='paymentSelected'])[3]</value>
      <webElementGuid>f250cc02-e16c-4888-991b-c16bbdcb99a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='whiteMid']/div[16]/div/div[5]/div/div/div/input</value>
      <webElementGuid>152e80d9-898e-4752-bebf-b61e2ae265d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/input</value>
      <webElementGuid>74402b23-7718-457f-9323-2b3b5668fb27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'paymentSelected' and @type = 'checkbox']</value>
      <webElementGuid>2e041d91-4e84-4a75-acd1-39d3d551a23b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
