<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No available TID_paymentSelected_1</name>
   <tag></tag>
   <elementGuidId>58b3aa6b-5e23-4502-b916-7cc6981e8fa1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MidDes.checkBoxInput.width30FloatLeft > input[name=&quot;paymentSelected&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='paymentSelected'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f1549705-1238-4244-bb96-4e16b1dc5adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>paymentSelected</value>
      <webElementGuid>06fd5270-84d8-4b61-93f4-ea6da6f25bc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b5c2ca3d-2394-429f-8c2f-336807cad36d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox checkBoxInp</value>
      <webElementGuid>ef5dd56f-5825-4b0a-ae97-8db6d0779dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>401002894510001</value>
      <webElementGuid>f0943f44-2e3a-4882-81e2-28f76b6455cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>e432a36f-03a3-4689-a5bc-5593ddd4d2c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>eb6bc90b-8875-4795-be67-29e868baf2b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;step1&quot;)/div[@id=&quot;barPadding&quot;]/div[@id=&quot;whiteMid&quot;]/div[@class=&quot;PayMent paddDetailBox2&quot;]/div[@class=&quot;groupLoop&quot;]/div[@class=&quot;Midloop&quot;]/div[@class=&quot;checkBoxDiv&quot;]/div[@class=&quot;width250FloatLeft boldHeaderText font14Black&quot;]/div[@class=&quot;MidDes checkBoxInput width30FloatLeft&quot;]/input[@class=&quot;checkbox checkBoxInp&quot;]</value>
      <webElementGuid>55d74c2c-72d4-46c8-8aff-33948c71bc8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='paymentSelected'])[3]</value>
      <webElementGuid>a260cb85-94f8-4584-b604-bb6340fa53b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='whiteMid']/div[16]/div/div[5]/div/div/div/input</value>
      <webElementGuid>14e6849f-614b-45c7-aa7b-fe17188435a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/input</value>
      <webElementGuid>5f8a8eec-190c-401d-ac5a-9f7fef0a37fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'paymentSelected' and @type = 'checkbox' and @checked = 'checked']</value>
      <webElementGuid>f530a1b5-58df-41ac-bb31-1a94c4d5634d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
