<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_test_paymentSelected</name>
   <tag></tag>
   <elementGuidId>742a51de-a095-47ab-b9a8-80b9de4761b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MidDes.checkBoxInput.width30FloatLeft > input[name=&quot;paymentSelected&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='paymentSelected'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c6d72cca-ca8a-4677-a36e-e5104420ede0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>paymentSelected</value>
      <webElementGuid>7d3dc14c-3477-4d95-b018-2ec1c16c1351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8668c2b0-972b-4db1-9ea6-3ab35dd934f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox checkBoxInp</value>
      <webElementGuid>8fa1728a-24b1-4c6f-bd74-25c390fc58b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>401002894510001</value>
      <webElementGuid>5939a99b-6ca1-4da1-989c-42e56c283f0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>49bbaec4-ee66-41d0-ba29-000f95350880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;step1&quot;)/div[@id=&quot;barPadding&quot;]/div[@id=&quot;whiteMid&quot;]/div[@class=&quot;paddDetailBox&quot;]/div[@class=&quot;groupLoop&quot;]/div[@class=&quot;Midloop&quot;]/div[@class=&quot;checkBoxDiv&quot;]/div[@class=&quot;width250FloatLeft boldHeaderText font14Black&quot;]/div[@class=&quot;MidDes checkBoxInput width30FloatLeft&quot;]/input[@class=&quot;checkbox checkBoxInp&quot;]</value>
      <webElementGuid>602f568e-a6c0-4ce8-aef8-59859c63d436</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='paymentSelected'])[3]</value>
      <webElementGuid>51b963c6-09c4-4436-b4f0-7840a0c14c2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='whiteMid']/div[16]/div/div[5]/div/div/div/input</value>
      <webElementGuid>15e1d8a7-35aa-4d22-abdb-a7b3e2d7ac1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/input</value>
      <webElementGuid>9d175296-a07e-402f-9276-5b88f108172f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'paymentSelected' and @type = 'checkbox']</value>
      <webElementGuid>b3fdc741-d97d-471f-a222-fdea24cb03c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='paymentSelected'])[6]</value>
      <webElementGuid>bce1b67b-0c4c-4fc0-be8b-a0b6098d2cca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='whiteMid']/div[16]/div[4]/div[2]/div/div/div/input</value>
      <webElementGuid>7f9adebe-0784-4614-ae7b-59a67174dfbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/div/input</value>
      <webElementGuid>028abead-dd13-4514-a263-71af39118f41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
