<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Staff Name_mobileUserId</name>
   <tag></tag>
   <elementGuidId>41cf187a-594c-4c7f-8787-10f72311f5a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mobileUserId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mobileUserId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8fd24a98-ade5-486f-9062-ae7f015049cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mobileUserId</value>
      <webElementGuid>afd673de-b77a-4852-984f-7470adad6e56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mobileUserId</value>
      <webElementGuid>f0b79431-b73f-4423-b9e5-8c015bb78e82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bcfb6460-54a9-428f-ba1e-0fb3bcc0d49b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>ab1d24a8-7a62-4cee-a581-f3837bd63a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f624458c-9f92-4234-9ae1-152a89a4cd65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mobileUserId&quot;)</value>
      <webElementGuid>786ce049-e9d5-4870-acff-50478df4d742</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mobileUserId']</value>
      <webElementGuid>a67beebf-3f0f-47f8-ba07-a96ebb65f98c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='whiteMid']/div[5]/input</value>
      <webElementGuid>2564b8c0-75fd-4e48-9c48-0a4077b82abc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>bd00e73d-3def-4b62-8400-6ccdf72c0532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mobileUserId' and @name = 'mobileUserId' and @type = 'text']</value>
      <webElementGuid>98714b52-39fe-4065-9c1e-a7940df8dae7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
