<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Merchant ID (MID)_mid</name>
   <tag></tag>
   <elementGuidId>6a101f3f-50cd-4379-8283-4f8bea7b7b1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eba625ab-9868-4dbe-a254-027ab7581ecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mid</value>
      <webElementGuid>f62d5e8e-5002-4b4d-ba9a-9c74d274496d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mid</value>
      <webElementGuid>f65132d3-e864-428e-9b44-2473b197dfd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f5f3fe9f-4d82-4086-8316-4a235f53470e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>6cc50c5f-4e51-4238-a2dc-5120fc799b60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e04a0e42-b543-4b68-ab39-eb76cea3a540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mid&quot;)</value>
      <webElementGuid>0f4c30d7-e8e7-42b1-9e0a-e77e762d48db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mid']</value>
      <webElementGuid>554d5955-26b4-41ab-82a4-3ff0d8772f6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group']/div[5]/div[2]/input</value>
      <webElementGuid>3889ae66-1830-4d41-999c-c50d8ef5ae1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/input</value>
      <webElementGuid>240ad1ef-76cc-44fe-90d6-ae12f7fe78e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mid' and @type = 'text']</value>
      <webElementGuid>c15bc3b2-d4f2-4c01-acd6-aab5ff9ba83d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
