<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_THB_maxAmountPerMonth</name>
   <tag></tag>
   <elementGuidId>89ec549a-ec65-4831-acc4-a777f8789237</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#maxAmountPerMonth</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='maxAmountPerMonth']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>376ff1af-09e0-462b-b502-92390a1ef66a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>maxAmountPerMonth</value>
      <webElementGuid>1b3704e3-6920-4a97-84b7-f7e55f4eb1ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>maxAmountPerMonth</value>
      <webElementGuid>48872838-7390-462d-9e45-bf6a04925c10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>55ea67c5-9390-4b4e-986c-683a92fdd148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>ebdc7ab6-b94c-4b1a-9ff4-dcf779c9b1b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>width270 defaultValue</value>
      <webElementGuid>3c434533-bf24-4b36-9bbc-067b6b2a7ef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>clickclear(this, '9,999,999')</value>
      <webElementGuid>901f3739-21e6-4b2c-a201-223a650a1750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>clickrecall(this, '9,999,999')</value>
      <webElementGuid>6ba04659-5cbf-4205-aaa3-8934065f1a05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>9,999,999</value>
      <webElementGuid>98a6eca6-119c-47ee-96e7-4b0a5e467393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>205ef922-d457-4b20-8cfd-8f2012e5eb02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maxAmountPerMonth&quot;)</value>
      <webElementGuid>1183eb48-c45b-4968-b4e0-c75bbf3c754d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='maxAmountPerMonth']</value>
      <webElementGuid>1ef55fe9-41e0-4585-8495-597ee6df8042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='whiteMid']/div[54]/input</value>
      <webElementGuid>d38c252f-119e-45b9-845f-8d77892fb0b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[54]/input</value>
      <webElementGuid>0e933a50-f6bc-49ae-8bfd-1785fe9a74e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'maxAmountPerMonth' and @name = 'maxAmountPerMonth' and @type = 'text']</value>
      <webElementGuid>44dbcf8b-4285-44cf-af6f-73760ffc8253</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
