<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_THB_maxAmountPerTransac</name>
   <tag></tag>
   <elementGuidId>f883a279-0edc-48d7-82fb-925fbf47d329</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#maxAmountPerTransac</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='maxAmountPerTransac']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9bcefd8d-1fde-4559-bfe3-2d0efb264cd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>maxAmountPerTransac</value>
      <webElementGuid>77cd8678-3cb4-41f6-8b33-ec4648c3332d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>maxAmountPerTransac</value>
      <webElementGuid>c67bdded-4485-4c2f-9d95-b1a35c4d71b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b519b88e-14de-424d-999d-b02f3a450177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>536af90e-72bf-473c-8e6c-8d28397b0beb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>width270 defaultValue</value>
      <webElementGuid>34e2102d-bda5-4a9a-ab05-a152dc40797a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>clickclear(this, '9,999')</value>
      <webElementGuid>0541c289-783b-4f80-9e59-c05f8c36f9aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>clickrecall(this, '9,999')</value>
      <webElementGuid>004a5141-2ff7-47e1-80d5-f90e0142f414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>9,999</value>
      <webElementGuid>a813dabe-962a-422d-97b6-ffc9120555e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0e9bf874-e671-47af-a966-726e1adfd43c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maxAmountPerTransac&quot;)</value>
      <webElementGuid>bec534e2-db4b-425b-9e9a-b12ac9796a27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='maxAmountPerTransac']</value>
      <webElementGuid>6d620a49-77a9-4542-b7a3-8ca1905e9225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='whiteMid']/div[51]/input</value>
      <webElementGuid>31009ca4-d405-440b-8d20-cbf07200f915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[51]/input</value>
      <webElementGuid>63163d2e-8772-4ede-9b2a-89753be35207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'maxAmountPerTransac' and @name = 'maxAmountPerTransac' and @type = 'text']</value>
      <webElementGuid>e06dd1b0-83b2-4cf6-aa24-3f033e399730</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
