<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Company Short Name_businessShortName</name>
   <tag></tag>
   <elementGuidId>716bd5e4-d045-4e17-83fa-ec7d06c74873</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#businessShortName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='businessShortName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2f501a37-2c52-4e73-94d8-c7034801db41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>businessShortName</value>
      <webElementGuid>30178dc5-2f43-4040-83c3-ba991a0f94aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>businessShortName</value>
      <webElementGuid>465e8c12-0c48-4946-b4c9-8a3925d82a06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>517765a6-4f09-43f2-a621-5a0b4db173dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>fc3a6931-4100-4e26-82f8-38252dab6fab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d093fb7e-23c7-4678-a9e3-b64a3f089b6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;businessShortName&quot;)</value>
      <webElementGuid>cfd72bc1-c9c1-4b6d-afd9-f536476d9dff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='businessShortName']</value>
      <webElementGuid>ccba5ca0-5c40-49da-9a63-923b1b523163</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='whiteMid']/div[5]/input</value>
      <webElementGuid>8a07cdf7-e4c8-4c8a-ad43-f3a533d29e49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>3d9740c9-fdae-46f1-bdc2-57178c20a202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'businessShortName' and @name = 'businessShortName' and @type = 'text']</value>
      <webElementGuid>bf8bca04-5019-47ef-a5e8-2943aa1c66b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
