<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Business Contact No_businessContact</name>
   <tag></tag>
   <elementGuidId>cc642ee1-e358-4f11-a8a5-4dc5c7709a61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#businessContact</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='businessContact']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ee8f1159-6430-47a3-8f50-3e2b1eecb23e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>businessContact</value>
      <webElementGuid>4f4d0b53-da1e-468f-a661-f72fe5f57912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>businessContact</value>
      <webElementGuid>bc1e9b14-94fe-447b-8c34-6828787563d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>689968bc-57cb-42c2-bcf8-b6b5ceaecc42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>ea22ac8e-331b-4ad2-bca1-0a54145e5aa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>defaultValue</value>
      <webElementGuid>9a8d9da9-02ae-40de-a504-42375d0d3596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>clickclear(this, '021234567')</value>
      <webElementGuid>1b1a8d7d-9cdd-446e-814d-e853e0de0785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>clickrecall(this, '021234567')</value>
      <webElementGuid>3b8fb206-08c9-423a-89f4-cdca3bbf9831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>021234567</value>
      <webElementGuid>0cbb8e4e-bcd7-4570-9e14-34ab85405eef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>eb9125aa-b5fd-4083-93a3-0dc782c6a686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;businessContact&quot;)</value>
      <webElementGuid>db1e67b5-0395-4c2f-8ea1-f33b5abe546b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='businessContact']</value>
      <webElementGuid>48d62347-0f9e-4c2d-bda1-47e5a41e2792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='whiteMid']/div[29]/input</value>
      <webElementGuid>b8c19cf8-8fca-4221-8785-6e238fadd89d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[29]/input</value>
      <webElementGuid>f8f7583e-7726-4af9-98cf-0a00f45a8094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'businessContact' and @name = 'businessContact' and @type = 'text']</value>
      <webElementGuid>9cca7c18-656c-44ed-bc66-60f8865df725</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
