<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contact No_contact</name>
   <tag></tag>
   <elementGuidId>3607577a-8898-48dc-94fb-b93ff50ca86d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#contact</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='contact']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>207cbba2-b886-47c1-89b2-5405b98a8a98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contact</value>
      <webElementGuid>eaa0c4f7-493c-4e1b-a01c-314009e28e26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>contact</value>
      <webElementGuid>4540e1a1-eec2-4a4e-bcd3-24b26ce797a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4b983648-8198-4fd8-afe0-620b842f37ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>0add07f5-f003-4af4-940b-b821d3ad0a60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>defaultValue</value>
      <webElementGuid>c20cbaa8-5e1b-4600-b919-d5394b20fa53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>clickclear(this, '08X1234567')</value>
      <webElementGuid>c33508e5-2504-487f-a7ea-065b34a05ec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>clickrecall(this, '08X1234567')</value>
      <webElementGuid>aaab05ae-2247-42fe-bc96-abdceb6d4774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>08X1234567</value>
      <webElementGuid>3ecde353-7267-413e-9782-e8bdecbcbad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0ef2accf-1e92-4d90-85cf-706eacea3649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contact&quot;)</value>
      <webElementGuid>b7e672f3-c18f-459a-8e04-dccebaeaae3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='contact']</value>
      <webElementGuid>4047f36a-6d44-4666-835a-54c9d7d91a19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='whiteMid']/div[45]/input</value>
      <webElementGuid>d31ea12b-f97a-4d1c-a88c-de61544cf2c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[45]/input</value>
      <webElementGuid>d183ab65-312c-4fcb-9e59-db4e37a40feb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'contact' and @name = 'contact' and @type = 'text']</value>
      <webElementGuid>68816a18-5916-46e1-ac48-a6dc09096093</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
