<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Business Registration Number (BRN)_bu_f5ee2c</name>
   <tag></tag>
   <elementGuidId>db32c393-2f8e-4a03-8e08-d48d320101b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#businessRegistrationNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='businessRegistrationNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4647c0f9-30e7-4510-8bbe-2e3cc4fba41d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>businessRegistrationNo</value>
      <webElementGuid>ef0ba73d-7181-4327-9da1-a0de20639f51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>businessRegistrationNo</value>
      <webElementGuid>20b435a5-1f09-434d-b7f9-ce9b9d1f58d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a43fb50e-58b4-4fc9-82f4-1fdf2b3549cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>87bde0d6-9873-4c8d-90d1-53a61ecbbd2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>152eea50-64de-4a70-b594-2ac7a72fbbe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;businessRegistrationNo&quot;)</value>
      <webElementGuid>6359ef01-2305-4988-a6c4-fcbb440f990b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='businessRegistrationNo']</value>
      <webElementGuid>8fc109be-8338-4b76-92c9-663515f04001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='whiteMid']/div[11]/input</value>
      <webElementGuid>a64c3bc5-581a-4526-ad0e-d7fe4e226dc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/input</value>
      <webElementGuid>ed4a8580-acaa-49a2-b8f1-74b5d65730e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'businessRegistrationNo' and @name = 'businessRegistrationNo' and @type = 'text']</value>
      <webElementGuid>e728c38a-bfc1-415b-a6bb-8754011b939b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
