<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Group Name_groupName</name>
   <tag></tag>
   <elementGuidId>118d1018-b293-4ad0-a622-742ad0f463b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#groupName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='groupName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>12190754-1390-47ff-a493-2aac0af43610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>groupName</value>
      <webElementGuid>1a9c75eb-8384-46c3-a893-a41e68c9b24a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>groupName</value>
      <webElementGuid>0f0c8311-f4f1-4ff2-9d63-13285155fe72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>600c4dd0-3128-4486-8f91-9ec5a5040178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>b93ab51b-81e6-4dac-856c-670992c3ff49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>713ea08e-d60d-4992-88e7-8e467e897177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;groupName&quot;)</value>
      <webElementGuid>c362508a-ff65-4459-89fc-8ff39ebe30cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='groupName']</value>
      <webElementGuid>4415625d-e2fe-4d30-b47d-16c75d892224</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group']/div[2]/input</value>
      <webElementGuid>224e4ad9-8227-4634-91bc-10225b2d814b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/input</value>
      <webElementGuid>49b57e90-8947-4230-8633-678c0dd8498c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'groupName' and @type = 'text']</value>
      <webElementGuid>64e05721-af43-42f3-93ad-6407f56c40cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
