<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Download Settlement Report_1</name>
   <tag></tag>
   <elementGuidId>6e2c2ae6-df74-4178-9b3e-f9ae54fb6ee1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='beigeMid']/div/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.paddLR30 > div.floatR > a.button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>eb1cec4f-80ca-4d59-a3d0-4a7cf59e0e23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>doPrintSettlementReport?itemid=141943</value>
      <webElementGuid>bcbbbfc1-1587-498c-8ecf-cfaac638efcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>27f6fb2c-6127-4fb1-8ef6-bddf0210271e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b881b126-3c03-4ab3-9ccd-98cc4b9833f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Download Settlement Report</value>
      <webElementGuid>bf2d78e1-9ac1-4616-a961-36f12847786b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rightMainContent&quot;)/div[@id=&quot;barPadding&quot;]/div[@id=&quot;beigeMid&quot;]/div[@class=&quot;paddLR30&quot;]/div[@class=&quot;floatR&quot;]/a[@class=&quot;button&quot;]</value>
      <webElementGuid>4327075f-7642-494b-a887-0ac8938770eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='beigeMid']/div/div[2]/a</value>
      <webElementGuid>74c9dbb8-fda1-453a-8553-834efea4558b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Download Settlement Report')]</value>
      <webElementGuid>37e58be1-4a37-432b-bcfa-31c22b768aea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The credit settlement for this batch was successful'])[1]/following::a[1]</value>
      <webElementGuid>2970232a-595f-4f3f-8e48-dc4011df7380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KB000000512534'])[1]/following::a[1]</value>
      <webElementGuid>9ff02a40-5900-4f02-9444-9e5cd12f1618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visa'])[1]/preceding::a[1]</value>
      <webElementGuid>f2fc5d88-a8a6-4d50-abaa-e61fc90251f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='THB 0.00'])[1]/preceding::a[1]</value>
      <webElementGuid>1a4d1def-aebd-4c85-bd96-c37fd804d527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Download Settlement Report']/parent::*</value>
      <webElementGuid>8a70fbc5-9ad3-4e64-b89c-95cd5dd87157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'doPrintSettlementReport?itemid=141943')]</value>
      <webElementGuid>501b83df-2097-46f7-841b-d7d675841f6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/a</value>
      <webElementGuid>f46091cc-8daa-4449-a2f0-65d67db87418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'doPrintSettlementReport?itemid=141943' and (text() = 'Download Settlement Report' or . = 'Download Settlement Report')]</value>
      <webElementGuid>21c1e40a-a2b7-4423-bd57-e8c162ee01e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
