<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Go</name>
   <tag></tag>
   <elementGuidId>ea5135cb-166f-48a5-baf7-256273443a94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#buttonGo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='buttonGo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>68ae5465-472e-4695-8c99-bfbd010184d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buttonGo</value>
      <webElementGuid>0af62ea9-2b50-4475-9480-8d1ab8f5a7f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font13Bold</value>
      <webElementGuid>2d08dfdd-878e-44c7-a4ac-baae0500ee56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:document.go856.submit();</value>
      <webElementGuid>ede3f0a2-d076-4a93-acf7-13e6dcacdd18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
				                		Go
				                	</value>
      <webElementGuid>14d1c3f5-90b8-4ecd-b9ce-9454e5711d25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;go856&quot;)/div[@class=&quot;floatL&quot;]/a[@id=&quot;buttonGo&quot;]</value>
      <webElementGuid>aee96eaa-f140-4f6c-9a7c-2e53dcd360b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>55988b91-e792-4cb6-a92f-2b58c0398e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buttonGo</value>
      <webElementGuid>3265c239-5753-4309-b0c6-c061bdbed019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font13Bold</value>
      <webElementGuid>1df9e12e-d044-40ed-91eb-868d8a70ee50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:document.go856.submit();</value>
      <webElementGuid>bc5c682c-7fe1-4b46-81a1-19f8c8683974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
				                		Go
				                	</value>
      <webElementGuid>d946140d-f236-47d1-b2f7-fc7644dd3202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;go856&quot;)/div[@class=&quot;floatL&quot;]/a[@id=&quot;buttonGo&quot;]</value>
      <webElementGuid>200ad591-c52e-4bbb-a913-96835407e4d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d7b4b45c-5759-4009-96a4-9135c455e813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buttonGo</value>
      <webElementGuid>2855e9ca-0dd8-49e5-bea7-608e0d5a9f3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font13Bold</value>
      <webElementGuid>19f289d6-ac2a-46c0-bc1a-48392817c9ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:document.go856.submit();</value>
      <webElementGuid>fa5c14a1-9689-4d18-8479-5507b477e230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
				                		Go
				                	</value>
      <webElementGuid>837a5c87-3765-4805-9557-d0b8a78ae113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;go856&quot;)/div[@class=&quot;floatL&quot;]/a[@id=&quot;buttonGo&quot;]</value>
      <webElementGuid>798bd38f-fdd5-4060-b6a4-5c947bbd8f23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='buttonGo']</value>
      <webElementGuid>dfad237f-23b2-4dc7-8aaa-f7aed09dc76f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='go856']/div[2]/a</value>
      <webElementGuid>9f3bd6a4-a3bd-4c4a-a941-f6793daec9df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Go')]</value>
      <webElementGuid>a7504ea5-937b-4755-85f3-cfa541e35312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suspend Bank User Access'])[2]/following::a[1]</value>
      <webElementGuid>4a5c05e6-2fba-428a-bde8-ec5964f9b5cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('=cmd|', &quot;'&quot;, ' /C calc', &quot;'&quot;, '!', &quot;'&quot;, 'A4', &quot;'&quot;, '')])[1]/preceding::a[1]</value>
      <webElementGuid>5a555fde-b9f1-4f02-88ae-04e7280db5e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Viewer'])[2]/preceding::a[1]</value>
      <webElementGuid>9ed5c6e1-2a88-4730-8db6-feaa1d03ea23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Go']/parent::*</value>
      <webElementGuid>f3efbb0f-7ed0-41a7-bf4e-c6a42c155393</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:document.go856.submit();')]</value>
      <webElementGuid>1a2ea70b-1d78-4947-a81b-9e6c1750b267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/a</value>
      <webElementGuid>6c25afd4-526b-4921-9141-3aa300e30a73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'buttonGo' and @href = 'javascript:document.go856.submit();' and (text() = '
				                		Go
				                	' or . = '
				                		Go
				                	')]</value>
      <webElementGuid>f608f99d-af94-40cd-b077-70f3e11a2a23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Details'])[2]/following::a[1]</value>
      <webElementGuid>58741500-d788-4071-ae0d-24f637b51d4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
