<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_201320142015201620172018201920202021_612be0</name>
   <tag></tag>
   <elementGuidId>ed1d3d21-89a7-448d-ab74-f2a287e9c9f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select.ui-datepicker-year</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//select[@onclick=&quot;DP_jQuery_1678341457764.datepicker._clickMonthYear('#fromdate');&quot;])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7b35b6c5-8a41-470c-8fb1-95dc7779bd61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-datepicker-year</value>
      <webElementGuid>0a9cf7f3-474e-45dc-a92d-204a34e6017a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>DP_jQuery_1678341457764.datepicker._selectMonthYear('#fromdate', this, 'Y');</value>
      <webElementGuid>784017fd-1695-4574-8ab5-dbe5010af9b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>DP_jQuery_1678341457764.datepicker._clickMonthYear('#fromdate');</value>
      <webElementGuid>91a32dde-d88b-46a8-8037-4ad705aa3bf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>91856242-0038-46c0-9f18-99d4bfe14287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>20132014201520162017201820192020202120222023</value>
      <webElementGuid>5d524b42-0b7a-4246-8089-97fa9743eb67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-datepicker-div&quot;)/div[@class=&quot;ui-datepicker-header ui-widget-header ui-helper-clearfix ui-corner-all&quot;]/div[@class=&quot;ui-datepicker-title&quot;]/select[@class=&quot;ui-datepicker-year&quot;]</value>
      <webElementGuid>6a8dce25-0e20-4ed3-b023-aba37c9736d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//select[@onclick=&quot;DP_jQuery_1678341457764.datepicker._clickMonthYear('#fromdate');&quot;])[2]</value>
      <webElementGuid>8ccb8776-ede8-4fd5-a433-1a856be592b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-datepicker-div']/div/div/select[2]</value>
      <webElementGuid>be98fbe5-e2af-47f2-a69c-c874cdcc1cd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::select[2]</value>
      <webElementGuid>9580c1f7-8629-4ab2-8413-2598cd2c1382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prev'])[1]/following::select[2]</value>
      <webElementGuid>b37877a8-d6ee-4ad1-94bb-3818ab7e0936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Su'])[1]/preceding::select[1]</value>
      <webElementGuid>a9adfadc-cfc0-4089-aa07-652a68be6e16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mo'])[1]/preceding::select[1]</value>
      <webElementGuid>2b29c968-8795-4eb9-a6c8-bad4c39a5b6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[2]</value>
      <webElementGuid>a6bf4953-f107-401c-97f0-c785d59f3959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = '20132014201520162017201820192020202120222023' or . = '20132014201520162017201820192020202120222023')]</value>
      <webElementGuid>f60d62a8-6024-4a81-ab20-9597ec915e1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
