<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Export CSV files</name>
   <tag></tag>
   <elementGuidId>e3f463d0-5a45-483d-a088-823077b655fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.button.btnL.exportCsv</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9dcd6796-09db-4af3-bbeb-910be0db4417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button btnL exportCsv</value>
      <webElementGuid>fbb73f40-7d3b-4fcc-8172-6050b98b3c4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/spocTransaction/exportCSV</value>
      <webElementGuid>2f7f6a85-2503-4b58-b8b1-0bc7da887c4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Export CSV files</value>
      <webElementGuid>f9d32490-d620-434a-b578-690040062546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paddCSV&quot;)/div[@id=&quot;beigeMid&quot;]/div[@class=&quot;textCenter&quot;]/a[@class=&quot;button btnL exportCsv&quot;]</value>
      <webElementGuid>8b7512dc-342e-47a7-af3e-b5290f68c605</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='']</value>
      <webElementGuid>540ee38f-f4b3-4d4f-9ef7-c992978472dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='beigeMid']/div/a</value>
      <webElementGuid>2d743654-020a-4d8d-851b-d4741b490db3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Export CSV files')]</value>
      <webElementGuid>dd8bd527-fcc5-4ba0-9985-762bc1e81f01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unsuccessful Transaction'])[1]/following::a[1]</value>
      <webElementGuid>95d8ca87-a70f-431a-b3fd-b7bb9efda12f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unsuccessful Transaction (EDC)'])[1]/following::a[2]</value>
      <webElementGuid>3349f637-dbcf-44a6-b853-4739c5972a41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export to Excel'])[1]/preceding::a[1]</value>
      <webElementGuid>728beed4-467b-4fbf-8cc8-6ef23b1502d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Spoc Transactions'])[1]/preceding::a[2]</value>
      <webElementGuid>527af8dd-339b-438a-b302-f40f1d18b946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Export CSV files']/parent::*</value>
      <webElementGuid>c0e7399a-22d9-4f76-86d4-05287a182ad8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/spocTransaction/exportCSV')]</value>
      <webElementGuid>d79ea3d0-ea3a-4217-a846-6231c2c246ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/div[2]/div/a</value>
      <webElementGuid>aedd8023-bdd7-4ce2-95e8-f311e74617cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/spocTransaction/exportCSV' and (text() = 'Export CSV files' or . = 'Export CSV files')]</value>
      <webElementGuid>60c809cf-7147-41e2-a74f-b0fc04c7bdb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
