<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Suspend MID Reason 1_remarks</name>
   <tag></tag>
   <elementGuidId>d676c2a9-4256-46f9-b261-8c81b64c25ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='remarks']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#remarks</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>2a7449fb-c228-4638-af10-d123def69ff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>remarks</value>
      <webElementGuid>531a0bf2-4ba7-4649-958b-b678a7e66786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>remarks</value>
      <webElementGuid>bfb99a30-9f2d-4b6e-ba99-ce3cbeba07c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>7f9dcdae-fc61-41fe-9d69-8ca7204a974e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>limitText(this.form.remarks,this.form.countdown,250);</value>
      <webElementGuid>c3e7d560-d3b8-495d-8aed-662bfdf6380c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>limitText(this.form.remarks,this.form.countdown,250);</value>
      <webElementGuid>027120c8-e5c4-4bcf-9e23-edd6741f282d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1ac92c20-2b75-421d-a957-5634a670c99f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;remarks&quot;)</value>
      <webElementGuid>1019f941-7598-4940-ac18-4632afb1babc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='remarks']</value>
      <webElementGuid>3fe07910-a6a2-4aa7-89d7-8602d810c5c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='whiteMid']/div[7]/textarea</value>
      <webElementGuid>ddf22346-8904-4c9d-b7b6-81213c6cf9d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>8b96b788-5bc3-409f-898a-d9f09b226c3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'remarks' and @name = 'remarks']</value>
      <webElementGuid>b7b00b66-41e3-4ac2-904e-9fc7a5a85bfc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
