<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_to_to</name>
   <tag></tag>
   <elementGuidId>4f8d6f5b-9957-443a-bd82-7f30e30c9826</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#todate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='todate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3b74d35f-65b1-4fd6-bf4d-32965d1c7639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>to</value>
      <webElementGuid>29128d56-9e48-475b-9f04-9ab85a918141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filterDate white hasDatepicker</value>
      <webElementGuid>5d05f5d2-3d09-4fe4-9ff0-a77959365dd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>245aa200-af5e-4842-93a6-c76eb3fc0b85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>todate</value>
      <webElementGuid>03a37ffe-a710-41e5-a575-1a4abd81f280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>End Date</value>
      <webElementGuid>61778927-de5d-4ff5-b5d2-0687bf9fe0a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>64f1feac-361f-4463-acac-748ea05d521b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b5acf419-b310-4d1a-a418-9772dc726523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;todate&quot;)</value>
      <webElementGuid>629db202-96b0-4854-9872-a387bc366de7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='todate']</value>
      <webElementGuid>2148287d-7c79-47e4-957d-63ba59dd6ba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='beigeMid']/form/div/div[5]/input[2]</value>
      <webElementGuid>6b24be28-fa30-4df0-9519-61b658e6d759</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>7ba03248-45d2-4be4-b2dc-6bf8ce987712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'to' and @type = 'text' and @id = 'todate']</value>
      <webElementGuid>503d2a83-5654-4049-ba59-5da10a4bea0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='beigeMid']/form/div/div[7]/input[2]</value>
      <webElementGuid>2e58f085-b058-487c-82f7-a795403d1dad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
