<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Limit Per TransactionTHB_maxAmountEDC_a062ad</name>
   <tag></tag>
   <elementGuidId>ae0299cf-45b3-4d58-8a77-48421f0dd75b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='maxAmountEDCPerTransac']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#maxAmountEDCPerTransac</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0d6bb2bd-d7f9-4173-b3c0-d59eaf2523e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>maxAmountEDCPerTransac</value>
      <webElementGuid>c7974e47-ab75-476c-997f-49ba136d3d77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>maxAmountEDCPerTransac</value>
      <webElementGuid>dc2db81d-09f2-4128-b7d6-113c1ae276a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>47e6863f-a86c-4292-baa3-c4af95f9ddc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>e8294de2-1e8f-46c0-a2fb-6c2422f17bf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>defaultValue</value>
      <webElementGuid>04755191-a497-4e8b-a9e3-ced53273fcd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>clickclear(this, '9,999')</value>
      <webElementGuid>5077de25-fcef-4db3-b26f-11473442297c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maxAmountEDCPerTransac&quot;)</value>
      <webElementGuid>409e3364-a5fc-4353-be34-1ee8049602cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='maxAmountEDCPerTransac']</value>
      <webElementGuid>0b028710-141b-441e-ae2d-882efbc81423</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group']/div[2]/div[8]/input</value>
      <webElementGuid>b91ae1e8-78eb-4689-889c-55eee1b14d64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/input</value>
      <webElementGuid>b9fc2906-dd7e-4bb2-971b-1a648339f564</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'maxAmountEDCPerTransac' and @name = 'maxAmountEDCPerTransac' and @type = 'text']</value>
      <webElementGuid>d7aef1a0-af0e-4c9f-a768-36d2bbcdeb81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
