<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Limit per MonthTHB_maxAmountEDCPerMonth</name>
   <tag></tag>
   <elementGuidId>44d446e6-5374-49af-b845-0b8d8d7067e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='maxAmountEDCPerMonth']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#maxAmountEDCPerMonth</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d1b1dbb9-c32f-42b1-b40e-8a4e8985d1cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>maxAmountEDCPerMonth</value>
      <webElementGuid>99cd9437-b6a4-413c-9489-13b2a2cd8a9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>maxAmountEDCPerMonth</value>
      <webElementGuid>80c0d230-9627-47be-b5d0-6ec989336602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8046d4ca-0b1c-4a35-9d85-ef5a30dbd014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>62401929-5afb-4e29-bb24-3b14f873e964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>defaultValue</value>
      <webElementGuid>2289c7d0-d021-485c-9311-42254b07074c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>clickclear(this, '9,999,999')</value>
      <webElementGuid>6a09c307-1f63-4cdf-b00d-1b5138413c8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>357196b6-6343-44c7-9a7a-a69e7cf78792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maxAmountEDCPerMonth&quot;)</value>
      <webElementGuid>5fcbe2de-9f11-454a-9833-baaa81dfad63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='maxAmountEDCPerMonth']</value>
      <webElementGuid>8df48349-d77e-4631-9eef-a05fc17d7105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group']/div[2]/div[11]/input</value>
      <webElementGuid>09df0048-c5a5-45c2-9e98-f71acd366618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/input</value>
      <webElementGuid>1ccb939f-e976-4e4a-a166-de24894999cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'maxAmountEDCPerMonth' and @name = 'maxAmountEDCPerMonth' and @type = 'text']</value>
      <webElementGuid>104ce480-235a-45dd-abc7-ceeceaeccc94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
