<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Go</name>
   <tag></tag>
   <elementGuidId>51fe9d7f-3f54-4969-9d8e-27d1728dcb76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#buttonGo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='buttonGo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c9c3635d-2115-477c-9475-099098328bfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buttonGo</value>
      <webElementGuid>40a16bbd-69b1-430f-921a-c5c9744ca932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font13Bold</value>
      <webElementGuid>e5a77b3f-4d2e-4564-a160-1f650f95d03a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:document.go30573.submit();</value>
      <webElementGuid>bc705409-06fe-4a61-a6b1-95810d4a1c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
				                		Go
				                	</value>
      <webElementGuid>75be6ebf-77d6-40e5-b921-324a55d2d36c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;go30573&quot;)/div[@class=&quot;floatL&quot;]/a[@id=&quot;buttonGo&quot;]</value>
      <webElementGuid>287c1239-e700-4c15-a573-ba6625d45959</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='buttonGo']</value>
      <webElementGuid>8a3987c9-6942-4a4f-9a4d-8c5afb7cbb30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='go30573']/div[2]/a</value>
      <webElementGuid>034d4e62-cc00-4c52-8fee-177c975444d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Go')]</value>
      <webElementGuid>011af021-2a04-422f-b399-86b4ddaa8831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Temporary Limit'])[2]/following::a[1]</value>
      <webElementGuid>2c45976b-5e09-48cb-96c7-9d897ec8b4c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='วันเกิด'])[1]/preceding::a[1]</value>
      <webElementGuid>d11f64cc-dff2-4331-a212-d15391ed6cf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='จิ วันเกิด'])[1]/preceding::a[1]</value>
      <webElementGuid>04fc4738-68ca-4582-915e-e7e16cec0977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Go']/parent::*</value>
      <webElementGuid>41e07406-882a-4c96-99e8-a6e8ae4806f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:document.go30573.submit();')]</value>
      <webElementGuid>d083eca0-e65d-4c73-ac39-3d78303045fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/a</value>
      <webElementGuid>6c17b238-9c18-41bc-99e9-afce5ae75431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'buttonGo' and @href = 'javascript:document.go30573.submit();' and (text() = '
				                		Go
				                	' or . = '
				                		Go
				                	')]</value>
      <webElementGuid>411100b2-b647-4008-865d-b785df081b51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
