<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Search</name>
   <tag></tag>
   <elementGuidId>02498226-c89f-4819-8533-8cbce2e24b4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;$(this).parents('form').submit();&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.button.btnL.btnDarkGrey</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f077bc1b-bb03-4bb5-8616-3008c3d80290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button btnL btnDarkGrey</value>
      <webElementGuid>0a2fab1d-1bae-41dc-9cc6-b3567b1226e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>89382462-9ff4-4687-8ad1-3b7c1b4766d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>$(this).parents('form').submit();</value>
      <webElementGuid>cadd90ed-66c6-437c-8ab4-9ffb5a66d0c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
					Search
				</value>
      <webElementGuid>ef4046ce-6094-494e-ab7a-b85100241931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rightMainContent&quot;)/div[@id=&quot;barPadding&quot;]/div[@id=&quot;beigeMid&quot;]/form[1]/div[@class=&quot;searchFR&quot;]/a[@class=&quot;button btnL btnDarkGrey&quot;]</value>
      <webElementGuid>e6257bbb-3987-41b4-b437-eceb7cd0611e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;$(this).parents('form').submit();&quot;]</value>
      <webElementGuid>fdba4a99-6893-4619-9673-b6fe0271b623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='beigeMid']/form/div/a</value>
      <webElementGuid>2f2d9f7b-f881-4a94-86dc-2dc9761c330f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Search')]</value>
      <webElementGuid>4234a80f-741b-4868-8abb-02d3e1ca67f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='K SHOP Company Summary'])[1]/following::a[1]</value>
      <webElementGuid>b40a3d0d-61e3-4df8-93a5-96c68a529120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add a Company'])[1]/following::a[2]</value>
      <webElementGuid>dcdafab2-8c7a-42db-8338-3605f11d5cba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Spoc Companies'])[1]/preceding::a[1]</value>
      <webElementGuid>0b78d2f0-abb4-4fc0-86be-6e034c30f439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/preceding::a[1]</value>
      <webElementGuid>4e9992be-759d-43c5-8982-7871c4a000cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Search']/parent::*</value>
      <webElementGuid>28b06d7f-af24-42de-aeb9-149cbdd8e683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0)')]</value>
      <webElementGuid>1ca35c32-0b07-4d90-b2bc-466e97727105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/a</value>
      <webElementGuid>35cc07c0-f61d-4baa-ad6c-d48306e321bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = '
					Search
				' or . = '
					Search
				')]</value>
      <webElementGuid>b89b1761-20c4-4ee0-ae18-716ac6ed6157</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
