<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Search_1</name>
   <tag></tag>
   <elementGuidId>967599be-fe44-4914-ac04-1462e20471de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@onclick=&quot;$(this).parents('form').submit();&quot;])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.formButton > a.button.btnL.btnDarkGrey</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ef44081d-ae4c-46b8-b908-6822cda19c2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button btnL btnDarkGrey</value>
      <webElementGuid>21805b87-5b74-4f6a-857f-04fa9d5446eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>15d28c4a-01f0-4370-a232-e78bf6913a72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>$(this).parents('form').submit();</value>
      <webElementGuid>f8ef2a5b-d178-4ab1-ad84-620c7b76772e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>54689944-27d8-4405-a59e-376be595ed2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rightMainContent&quot;)/div[@id=&quot;barPadding&quot;]/div[@id=&quot;beigeMid&quot;]/form[1]/div[@class=&quot;filterForm&quot;]/div[@class=&quot;formButton&quot;]/a[@class=&quot;button btnL btnDarkGrey&quot;]</value>
      <webElementGuid>eb7ca9e5-39e3-4e9c-9455-74b11d5ee286</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@onclick=&quot;$(this).parents('form').submit();&quot;])[2]</value>
      <webElementGuid>4db9c363-035e-41bc-b31f-c1166cf1c00b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='beigeMid']/form/div/div[8]/a</value>
      <webElementGuid>4cf05ab0-3e57-41c6-8428-26f143615b24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Search')])[2]</value>
      <webElementGuid>ab3cef84-ed42-4083-9d9d-ff1c1a3a9136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date'])[1]/following::a[1]</value>
      <webElementGuid>4d680bcb-eae0-4073-b180-a9f8e6896df3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Records: 572'])[1]/preceding::a[1]</value>
      <webElementGuid>7bf775b1-52f2-4742-9144-3aa5977dfe63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page 1 of 39'])[1]/preceding::a[1]</value>
      <webElementGuid>3467c5bf-bd86-489e-9276-ccbbd2b25c66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[2]</value>
      <webElementGuid>e03c125b-1f09-4485-8949-6b84dd24a854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/a</value>
      <webElementGuid>9701eec8-2e44-4ec1-bcc9-0defe925fa81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = 'Search' or . = 'Search')]</value>
      <webElementGuid>6a39c62c-f83a-43fb-b68c-4e219b156935</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
