<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Reset Password_ctaBottom</name>
   <tag></tag>
   <elementGuidId>3931e60d-83ac-470e-8bb4-96aa46dd282d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctaBottom</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctaBottom']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bf1914de-0af6-42e3-b84c-515b8130d91f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctaBottom</value>
      <webElementGuid>5e75a86b-2efc-4a67-8fcf-aeaec57d34a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctaBottom&quot;)</value>
      <webElementGuid>bd82ed1a-e5c9-40a3-83bb-6f13f9a18b85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ctaBottom']</value>
      <webElementGuid>ebdaf45c-616f-4f39-92c6-ba245b51ee2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='barPadding']/div[6]</value>
      <webElementGuid>b13c8f01-be25-4486-983d-6f7927fdfb8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]</value>
      <webElementGuid>78891116-61c6-45af-aea3-3c93fcedbb6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ctaBottom']</value>
      <webElementGuid>e6e4af77-cac1-43d4-b80c-c8023df33a9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
