<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Terminal ID (TID)_tid</name>
   <tag></tag>
   <elementGuidId>c9d5dbb0-8108-4c05-8895-2ad69a224785</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;tid&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='tid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>852f81d9-044b-4d5e-b19d-4cb925da5e05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filter white</value>
      <webElementGuid>e4bf1ded-2425-4bb0-b9a3-7ef169967ee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3070d343-6648-46ab-9d53-553cb18c440a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tid</value>
      <webElementGuid>6262bc49-591c-487a-8a5c-8b26ac3ec9c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a9088244-e594-4b6a-993e-8813b241d5cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;beigeMid&quot;)/form[1]/div[@class=&quot;filterForm&quot;]/div[@class=&quot;formInput&quot;]/input[@class=&quot;filter white&quot;]</value>
      <webElementGuid>dcc12fd9-0f7c-4f3f-9558-38ba2c4b3aee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='tid']</value>
      <webElementGuid>34139b5e-40d5-4f3f-babf-b959475b415a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='beigeMid']/form/div/div[6]/input</value>
      <webElementGuid>8e619cd2-a489-4859-8d4b-faa7239583a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>343239a7-0dd8-4dcd-afa0-17457f4a539c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'tid']</value>
      <webElementGuid>7b0b025b-a99b-48f2-bb41-9d5d5f6bc802</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='beigeMid']/form/div/div[4]/input</value>
      <webElementGuid>c8b524f0-192c-4f4c-9e91-6676e4a05039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>76d8f034-43c1-4005-a2ed-620107b8c6c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
