<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MID_mid</name>
   <tag></tag>
   <elementGuidId>c1c14c7a-be38-4a32-85e9-af35cd51d9bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;mid&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='mid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>56b3b0f3-e97f-42cc-9342-1ca2ff757061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filter white</value>
      <webElementGuid>119465c2-2227-412e-b53d-d350ae50f8f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>99cd52f5-65cd-4c9b-99ae-cd09da6f297a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mid</value>
      <webElementGuid>34e1fbc6-becf-4f48-a0cd-7226c63f9e11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c149b4f2-2e46-4813-82de-072b0eea93ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rightMainContent&quot;)/div[@id=&quot;barPadding&quot;]/div[@id=&quot;beigeMid&quot;]/form[1]/div[@class=&quot;filterForm&quot;]/div[@class=&quot;formInput&quot;]/input[@class=&quot;filter white&quot;]</value>
      <webElementGuid>9ff30d2f-8c18-495b-898d-da4d3da2fd91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='mid']</value>
      <webElementGuid>298c0f4e-1e47-4b4a-afd0-8dfc286ff38d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='beigeMid']/form/div/div[2]/input</value>
      <webElementGuid>317d122f-1d83-4d7b-becd-306f7528547f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3af4ae7a-464f-4b2e-9184-f4779a96cf4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'mid']</value>
      <webElementGuid>cd60eaea-a6ee-4454-a1ec-4c9b1c940793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='mobileUserId']</value>
      <webElementGuid>af04e419-5c06-4da8-b91e-2eaa2982ecce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='beigeMid']/form/div/div[4]/input</value>
      <webElementGuid>c1220ac9-9461-4a33-aeb9-1b2bce4955b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>0ed19957-48fd-4537-b7cf-a24a1a6f82d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'mobileUserId']</value>
      <webElementGuid>85a73d6b-3953-4195-9ec0-5c08e04a7468</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
