<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_K SHOP Company Summary</name>
   <tag></tag>
   <elementGuidId>d4256010-0a64-4b2e-bf25-aa01a8ffc87a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.selected > a > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='leftPanel']/li[3]/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>853c5ae4-d765-46d6-a041-c3598e9839f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>K SHOP Company Summary</value>
      <webElementGuid>8c11ca47-e258-40b8-87c9-f43d5819d9ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leftPanel&quot;)/li[@class=&quot;selected&quot;]/a[1]/div[1]</value>
      <webElementGuid>a4384f88-3959-418b-8cf7-8b975d0e9eab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>144f7191-d50b-4015-9cbb-1b9babcaae18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>K SHOP Company Summary</value>
      <webElementGuid>23eee87d-ca1d-43d8-99ca-810576bc3a73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leftPanel&quot;)/li[@class=&quot;selected&quot;]/a[1]/div[1]</value>
      <webElementGuid>10948546-7b8c-4a33-90cd-16f1cd91c417</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='leftPanel']/li[3]/a/div</value>
      <webElementGuid>23cb67ef-a6c9-4d05-b7c0-1b9f04dea153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add a Company'])[1]/following::div[1]</value>
      <webElementGuid>62b9e2e3-ea3f-4e21-9ff7-e17981c53b1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company Summary'])[1]/following::div[2]</value>
      <webElementGuid>188789e3-3e5f-4e20-b2f6-ac09f147710a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Temporary Limit'])[1]/preceding::div[3]</value>
      <webElementGuid>ef97b98f-b58f-4a05-979a-246348edc16d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Temporary Limit'])[2]/preceding::div[5]</value>
      <webElementGuid>902db559-c8ef-4483-a40d-754bea15730c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='K SHOP Company Summary']/parent::*</value>
      <webElementGuid>3fdb92a5-e565-417c-96d1-ee7f4df4da19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/div</value>
      <webElementGuid>ef4bbd0e-6890-46f5-a094-004ac45ecb1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'K SHOP Company Summary' or . = 'K SHOP Company Summary')]</value>
      <webElementGuid>4dd64d91-3f8c-4261-a28e-f10483972364</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
