<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Submit</name>
   <tag></tag>
   <elementGuidId>d5161e72-e252-4726-867a-fa883d186f11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctaMid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctaMid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>474ed0c4-afb6-4d7c-8979-2ebede34e3dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctaMid</value>
      <webElementGuid>55313274-e856-45ad-913b-d31b3230f9ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
						Submit
						
					</value>
      <webElementGuid>9056c145-7ee7-4a83-9195-1d6406a064e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;step1&quot;)/div[@id=&quot;barPadding&quot;]/div[@id=&quot;ctaMid&quot;]</value>
      <webElementGuid>ac617d7c-32cd-4f03-a6fe-ae05a621fff3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ctaMid']</value>
      <webElementGuid>d79761e4-4a15-4439-bced-10047d32a854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='barPadding']/div[4]</value>
      <webElementGuid>927f2f50-37d6-460a-9f13-1a5bb94695b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Optional)'])[1]/following::div[4]</value>
      <webElementGuid>ce63177d-5866-4fe1-b729-57700bb7aca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Automate'])[2]/following::div[4]</value>
      <webElementGuid>3299c086-5110-4348-b627-47c901469784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company Name'])[2]/preceding::div[4]</value>
      <webElementGuid>23e4c283-09d4-42f2-adda-f81dcc0d82f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[4]</value>
      <webElementGuid>0a7ed272-1f68-4b36-9f98-de2ec7b5c679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ctaMid' and (text() = '
						Submit
						
					' or . = '
						Submit
						
					')]</value>
      <webElementGuid>e7673218-2fa7-41cc-b6bd-393228417419</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
