<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_</name>
   <tag></tag>
   <elementGuidId>3fd2f4e5-463b-418e-a0fa-d8ccebe865d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tempPerTranError']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tempPerTranError</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>facf45bc-683e-48cd-ad29-736ffb1e5bdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tempPerTranError</value>
      <webElementGuid>903a1962-960e-4592-870c-d631396c09d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>errorMsg hidden</value>
      <webElementGuid>5a16c06f-3bd0-440d-9e48-77f63286c8f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
												วงเงินชั่วคราวต่อรายการต้องมากกว่าวงเงินถาวรต่อรายการ
											</value>
      <webElementGuid>22c25b54-9ac8-4140-93a4-65904fe9cdce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tempPerTranError&quot;)</value>
      <webElementGuid>8183a7c5-39c0-4698-bba4-e4233a62be33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6da02fb9-225e-4d67-8c8b-e54bb3b4afcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formInputS</value>
      <webElementGuid>034ab406-79b4-469e-8f74-cc19d98cb0ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
											
											
												กรุณาใส่จำนวนเงินหรือย้อนกลับ
											
										</value>
      <webElementGuid>1a9f8655-6196-4fd3-b518-6d693b5a0fca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;temp&quot;)/div[@class=&quot;formInputS&quot;]</value>
      <webElementGuid>7cc41cb3-6d50-4b85-a9a2-62b918347317</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='tempPerTranError']</value>
      <webElementGuid>29b5583d-6c86-4f48-bef5-04b98735bf62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='temp']/div[2]/div</value>
      <webElementGuid>cff8cd9d-897c-4cad-8412-f05a4bc84175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Temporary Limit Per Transaction:'])[1]/following::div[2]</value>
      <webElementGuid>5ddbcebc-70ca-4c2a-a5bb-7bc9a42a6048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div[2]/div</value>
      <webElementGuid>ca7e43eb-adf7-4616-9648-d46f11d7fbdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'tempPerTranError' and (text() = '
												วงเงินชั่วคราวต่อรายการต้องมากกว่าวงเงินถาวรต่อรายการ
											' or . = '
												วงเงินชั่วคราวต่อรายการต้องมากกว่าวงเงินถาวรต่อรายการ
											')]</value>
      <webElementGuid>65a8e102-0617-4f2a-9c71-389724b447cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='temp']/div[5]</value>
      <webElementGuid>374dfd33-b2e3-4888-a72c-e792bd0437f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Temporary Limit Per Month:'])[1]/following::div[1]</value>
      <webElementGuid>79edc16e-cdfa-4025-b215-ebeb00a5e513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expire Date Temporary Per Month:'])[1]/preceding::div[2]</value>
      <webElementGuid>e7bbfc04-30ea-4ba4-8932-ce67cc7cd480</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div[5]</value>
      <webElementGuid>d3689f57-4d2f-453a-abc4-46fb9da3d93e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
											
											
												กรุณาใส่จำนวนเงินหรือย้อนกลับ
											
										' or . = '
											
											
												กรุณาใส่จำนวนเงินหรือย้อนกลับ
											
										')]</value>
      <webElementGuid>8903907b-92c3-4962-8791-2b5f36611ae9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
