<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Expire Date Temporary PerTransaction_ui_bf3f97</name>
   <tag></tag>
   <elementGuidId>dc45ee74-fa54-45f1-aca7-737b0052ba74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='temporaryPerTransaction']/div[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.ui-datepicker-trigger</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6fc482e3-b9ef-48ba-995c-a4876bfcc852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-datepicker-trigger</value>
      <webElementGuid>af338f33-dc02-4b25-9f31-bd8e854df646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/resources/images/icon/datepicker/btn_calendar.png</value>
      <webElementGuid>25fa6ef7-387c-4f8d-bec4-5af488ea56da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>...</value>
      <webElementGuid>1455c4b3-5c7d-4d79-946b-5281d0974b91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>...</value>
      <webElementGuid>f650af7e-0b5a-4e22-a976-a60a7f91b183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;temporaryPerTransaction&quot;)/div[@class=&quot;formInputS&quot;]/img[@class=&quot;ui-datepicker-trigger&quot;]</value>
      <webElementGuid>94a0193f-2437-4d7e-9b50-c5e5bc88c3b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3df55412-9c18-434f-8f9e-f674f77db5dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-datepicker-trigger</value>
      <webElementGuid>60cb2ed4-a34e-404e-ac6a-4e9dcd7afff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/resources/images/icon/datepicker/btn_calendar.png</value>
      <webElementGuid>333968ae-57cf-4310-bfc3-2ae5c1a32159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>...</value>
      <webElementGuid>6972e899-6594-45f6-9d16-93755517e905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>...</value>
      <webElementGuid>fdc62e67-63c8-4bd0-be05-52930db9d55e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;temporaryPerTransaction&quot;)/div[@class=&quot;formInputS&quot;]/img[@class=&quot;ui-datepicker-trigger&quot;]</value>
      <webElementGuid>e06eb85a-7a31-495f-ac1f-25b57de49eba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>cc59f948-457b-4a36-b589-a52571012980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-datepicker-trigger</value>
      <webElementGuid>e8106345-175f-4195-8f9d-c7f560721b21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/resources/images/icon/datepicker/btn_calendar.png</value>
      <webElementGuid>47b183a5-1fad-4b14-b528-0509c171eff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>...</value>
      <webElementGuid>64e369ee-4857-437c-8cbe-f4d7f73845d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>...</value>
      <webElementGuid>cb908d64-94b4-4131-8679-351e78929ddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;temporaryPerTransaction&quot;)/div[@class=&quot;formInputS&quot;]/img[@class=&quot;ui-datepicker-trigger&quot;]</value>
      <webElementGuid>d4867baa-35aa-4b36-b0d8-063a73048bc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a4aeff17-e963-4665-a081-1acb3de8e7ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-datepicker-trigger</value>
      <webElementGuid>2497d6fc-2f88-4ea7-a958-6dd35a6182b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/resources/images/icon/datepicker/btn_calendar.png</value>
      <webElementGuid>48f046b1-0129-4711-9bc8-50a25565210f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>...</value>
      <webElementGuid>089243e3-118a-4376-adbe-47ad375da9c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>...</value>
      <webElementGuid>0cb67fed-b8fe-4a0e-bdb1-341f94ee48b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;temporaryPerTransaction&quot;)/div[@class=&quot;formInputS&quot;]/img[@class=&quot;ui-datepicker-trigger&quot;]</value>
      <webElementGuid>3e77767a-2484-4915-823c-87cf6c1c1535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d7b8d665-87ef-48d3-ba9f-c7d4a8df5417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-datepicker-trigger</value>
      <webElementGuid>6631074c-fe16-4b88-8326-a8ee8d397944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/resources/images/icon/datepicker/btn_calendar.png</value>
      <webElementGuid>bafb3ca2-aa74-42f2-b253-2026477f583a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>...</value>
      <webElementGuid>2306b13e-bd6e-480d-b806-75d73b534930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>...</value>
      <webElementGuid>c62b91a0-e928-41e0-a910-73c68c90e8b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;temporaryPerTransaction&quot;)/div[@class=&quot;formInputS&quot;]/img[@class=&quot;ui-datepicker-trigger&quot;]</value>
      <webElementGuid>4fa7a432-ed6a-4302-bc82-afee142f3118</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='temporaryPerTransaction']/div[2]/img</value>
      <webElementGuid>20b23448-997f-42ee-a74a-dc23e14c73e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='...']</value>
      <webElementGuid>965e5ab8-240e-4067-933b-be3ddd7494db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>c15521d8-8377-48ef-94ff-e0792b7673da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/resources/images/icon/datepicker/btn_calendar.png' and @alt = '...' and @title = '...']</value>
      <webElementGuid>0e5010c4-f323-49d6-9414-554581261a2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='temporaryPerTransaction']/div[2]/img[2]</value>
      <webElementGuid>35bbacb3-5e8f-4b34-ba74-654bc6e7906b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='...'])[2]</value>
      <webElementGuid>67676c01-df05-4b5f-8ef0-0f543a89c084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img[2]</value>
      <webElementGuid>ee1c3f2a-3aba-475f-ac15-184754d49969</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
