<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Expire Date Temporary PerTransaction__4f87ae</name>
   <tag></tag>
   <elementGuidId>f7e900ee-7bf7-48c3-b687-abcf5c7d2052</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#datepickerAddTemporaryPerTransactionExpireDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='datepickerAddTemporaryPerTransactionExpireDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fd141211-2d31-4f83-8324-b074601332f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>033485be-7724-4d8a-bb1c-57e1af2f10df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>datepickerAddTemporaryPerTransactionExpireDate</value>
      <webElementGuid>ddb42de9-a69a-4904-a975-c364ae3d8cda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>datepickerAddTemporaryPerTransactionExpireDate</value>
      <webElementGuid>adbaa280-80dd-45c4-8b65-aaa60140ac41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filterDate white hasDatepicker</value>
      <webElementGuid>8353c03f-f5a6-4d29-8867-72a454f9503e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>End date</value>
      <webElementGuid>71461464-be75-4ce1-ac63-4e323c65f303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6ee33978-58e1-480e-b531-b7fcf780fb4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datepickerAddTemporaryPerTransactionExpireDate&quot;)</value>
      <webElementGuid>6fef62dc-c07a-483d-a89e-36da43f02928</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='datepickerAddTemporaryPerTransactionExpireDate']</value>
      <webElementGuid>fd257656-51df-4e43-864f-2fee1e9d5291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='temporaryPerTransaction']/div[2]/input[2]</value>
      <webElementGuid>53055f34-f212-497a-b90b-66c28f24810e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input[2]</value>
      <webElementGuid>931ef57f-9d34-4898-b7b7-00e3db5ef10e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'datepickerAddTemporaryPerTransactionExpireDate' and @id = 'datepickerAddTemporaryPerTransactionExpireDate']</value>
      <webElementGuid>0915bc7c-b942-4f95-ad0d-bf721f32d0bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
