<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Expire Date Temporary Per Month_tempP_07af40</name>
   <tag></tag>
   <elementGuidId>9a6d278f-c551-4c42-9d89-65796cf416fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tempPerMonthEndDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tempPerMonthEndDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3c6d22e5-a37a-45b5-b0d0-d9080d697179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1521a8e9-2dc5-4193-95d0-48469f874d92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tempPerMonthEndDate</value>
      <webElementGuid>9e5c36af-f479-498b-b756-63504793bf5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tempPerMonthEndDate</value>
      <webElementGuid>f82d4e6b-76a0-4e64-8eb8-9b485678acf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filterDate white hasDatepicker</value>
      <webElementGuid>e06ec7ee-30cc-4c68-ac00-3137c47b95e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>End date</value>
      <webElementGuid>67dadbb3-66ae-4f4c-9f54-0b8a0398c19f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c375c95a-a112-487d-8dac-ec5d705ab5ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tempPerMonthEndDate&quot;)</value>
      <webElementGuid>3889fd3e-8f34-4634-bf25-4d50dd12a185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e1619d00-5323-4aa0-91e5-435f4313f350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c282ff58-9f8b-4de1-992a-6b403b792c8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tempPerMonthEndDate</value>
      <webElementGuid>c50d7c7b-d000-4e95-94ff-3a50790897e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tempPerMonthEndDate</value>
      <webElementGuid>ef328532-ba55-4ef9-bb4e-31c0e1cb55c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filterDate white hasDatepicker</value>
      <webElementGuid>55965a87-54f9-4ae7-a40b-e9d5491f32ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>End date</value>
      <webElementGuid>c52d3e71-bf46-4887-896b-a7697c1b2a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>26c9f835-7ee4-4fae-bbab-47d3876ad133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tempPerMonthEndDate&quot;)</value>
      <webElementGuid>5ebf8378-431b-44e0-875c-2b41b34e2282</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tempPerMonthEndDate']</value>
      <webElementGuid>c12a0dd3-e1ad-4932-aa5e-3377a36c6a38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='temporaryPerMonth']/div[2]/input[2]</value>
      <webElementGuid>642c7730-f3b5-45b2-83d8-39a2a3131dc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/input[2]</value>
      <webElementGuid>08784fcd-4500-4e63-b55b-4340a90f1f61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'tempPerMonthEndDate' and @id = 'tempPerMonthEndDate']</value>
      <webElementGuid>fadd80e5-750b-4f94-b3b0-8113313319c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
