<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Expire Date Temporary Per Month_datep_f111e0</name>
   <tag></tag>
   <elementGuidId>1615d57b-6eee-45ee-97bc-a8f7882c4434</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#datepickerAddTemporaryPerMonthStartDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='datepickerAddTemporaryPerMonthStartDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6683221d-3cec-4d0d-8162-9fc6bbc268d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a588df11-7e90-4c7d-aacf-ac2b4a985bb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>datepickerAddTemporaryPerMonthStartDate</value>
      <webElementGuid>7647d4d1-1353-4d72-9155-22a77a01426b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>datepickerAddTemporaryPerMonthStartDate</value>
      <webElementGuid>4a73defe-a1a4-4716-b034-5befde7aca01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filterDate white hasDatepicker</value>
      <webElementGuid>fc3839d3-c254-48f8-bd39-22322b57d1ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Start date</value>
      <webElementGuid>df4c7033-6206-410b-93cb-6d54cb74fff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0b8b820e-0760-434b-8d25-c2ddb54e1113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datepickerAddTemporaryPerMonthStartDate&quot;)</value>
      <webElementGuid>311e801b-d242-40ad-8409-c6d59bd4f83b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='datepickerAddTemporaryPerMonthStartDate']</value>
      <webElementGuid>e41cc3bf-52db-4c85-a179-0fbf389c5bd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='temporaryPerMonth']/div[2]/input</value>
      <webElementGuid>f8a5a98b-2909-4bff-af9c-f1d2819bd6ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/input</value>
      <webElementGuid>57b5ef77-c96c-4835-b117-38ec830e3c72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'datepickerAddTemporaryPerMonthStartDate' and @id = 'datepickerAddTemporaryPerMonthStartDate']</value>
      <webElementGuid>f31126d0-8efc-4b7e-8969-ba34696e0eff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
