<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Temporary Limit Per Transaction_tempE_c475cf</name>
   <tag></tag>
   <elementGuidId>d619454b-ed6e-470b-a7ca-3b37c5d706d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tempEDCPerTransac</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tempEDCPerTransac']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>800e7026-705d-49b0-8753-a49362ef247e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tempEDCPerTransac</value>
      <webElementGuid>8641b57e-3611-451e-8393-ba1e202a9a20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tempEDCPerTransac</value>
      <webElementGuid>2be66326-d684-4cf0-9f3a-5ad3b58d91ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3780d7be-4f91-447e-b244-4bbf84576837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d58bb08c-427b-4a23-85ad-db13f9be1661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tempEDCPerTransac&quot;)</value>
      <webElementGuid>fd28a94d-199c-4c18-a8c6-979505f783b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tempEDCPerTransac']</value>
      <webElementGuid>9ae62381-dfa7-4495-a20e-7eb306e202b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='temp']/div[2]/input</value>
      <webElementGuid>a6fa2d83-4f33-4cad-b6e4-d1eb5a06ce18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>cac2719a-e15e-4bd7-8af1-5c7c91c9691f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tempEDCPerTransac' and @name = 'tempEDCPerTransac' and @type = 'text']</value>
      <webElementGuid>bb7690fd-a92a-4d55-8b4f-04e206d8be51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
