<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Temporary Limit Per Month_tempEDCPerMonth</name>
   <tag></tag>
   <elementGuidId>59c4e24d-478b-43c8-ab28-d97622fa18ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tempEDCPerMonth</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tempEDCPerMonth']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4212ae09-0cde-40e9-8765-5d2e9f914cd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tempEDCPerMonth</value>
      <webElementGuid>265f6447-5a70-43eb-9464-9a6746584d49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tempEDCPerMonth</value>
      <webElementGuid>9169c312-b586-47f6-902c-82e04b8a095c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1dfb1ce8-ee40-47bf-bf1f-41de2ea99d81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>showDateMonthGroup()</value>
      <webElementGuid>561229b2-9f6e-48f9-a5ea-a580fede524b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tempEDCPerMonth&quot;)</value>
      <webElementGuid>b1725878-a92e-4abe-8b69-3fc6f412eb8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tempEDCPerMonth']</value>
      <webElementGuid>ec2b28e1-7099-4cc4-a781-87d6cb85c9ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='temp']/div[5]/input</value>
      <webElementGuid>897f05e7-7d46-4c62-9ede-f23e1a686623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>413e0899-ffeb-4edc-a2be-8001a628ff67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tempEDCPerMonth' and @name = 'tempEDCPerMonth' and @type = 'text']</value>
      <webElementGuid>9f319c8e-ea66-4981-a067-a4069e38c947</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
