<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Expire Date Temporary Per Month_datep_d5b0b0</name>
   <tag></tag>
   <elementGuidId>82ecb483-d03d-4b61-bd11-2aace3a3e09f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#datepickerAddTemporaryPerMonthExpireDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='datepickerAddTemporaryPerMonthExpireDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7c0f4ed1-753b-49e6-b7cb-cb876978458a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7aa9e641-0fac-4beb-8f53-c91d69469604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>datepickerAddTemporaryPerMonthExpireDate</value>
      <webElementGuid>4fc47b9f-1a20-46cd-915d-a29f28b66429</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>datepickerAddTemporaryPerMonthExpireDate</value>
      <webElementGuid>ed1e8884-345b-4d90-8f06-333a40992b4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filterDate white hasDatepicker</value>
      <webElementGuid>1c080ed1-1ed4-47e6-81fd-801254bf7006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>End date</value>
      <webElementGuid>45bfde85-9603-469d-8a9d-65028d8a7c08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>03a59e54-5b44-4f32-a349-d6b3c9409bd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datepickerAddTemporaryPerMonthExpireDate&quot;)</value>
      <webElementGuid>34aa7b6a-80cd-4f55-92c8-13049b1c9339</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='datepickerAddTemporaryPerMonthExpireDate']</value>
      <webElementGuid>53fd806d-5a37-4f13-bbf5-d150673d19f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='temporaryPerMonth']/div[2]/input[2]</value>
      <webElementGuid>c828317b-8776-4dc8-9a0b-01e92c98989f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/input[2]</value>
      <webElementGuid>2bcf17de-2524-41e0-a3d1-a4b268e1aad9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'datepickerAddTemporaryPerMonthExpireDate' and @id = 'datepickerAddTemporaryPerMonthExpireDate']</value>
      <webElementGuid>adf6205f-e518-4bd3-9071-cf382481ccdb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
