<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Expire Date Temporary PerTransaction__14d80c</name>
   <tag></tag>
   <elementGuidId>197e4c41-ae4a-4880-b432-2c53084b08df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#datepickerAddTemporaryPerTransactionStartDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='datepickerAddTemporaryPerTransactionStartDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7a857f6e-504b-4222-889e-d38ed25d498e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0357ac95-d4e3-4bbd-b991-2e352736f601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>datepickerAddTemporaryPerTransactionStartDate</value>
      <webElementGuid>4400bb8c-ab14-4b04-ae0f-04318a8ea639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>datepickerAddTemporaryPerTransactionStartDate</value>
      <webElementGuid>d76ef521-55a3-4804-92bf-ce8a4700767d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filterDate white hasDatepicker</value>
      <webElementGuid>34ef4169-397f-4b95-8d03-2ef0318dcbf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Start date</value>
      <webElementGuid>bbeefe28-66b1-4daf-a35e-4e6440cf7857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datepickerAddTemporaryPerTransactionStartDate&quot;)</value>
      <webElementGuid>b7114663-4725-43ac-aae9-6d99d22368b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8be62c2c-fd70-4db2-b30b-f948d39b0d9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='datepickerAddTemporaryPerTransactionStartDate']</value>
      <webElementGuid>7a7131af-cc07-4b3c-89e4-95065c32400b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='temporaryPerTransaction']/div[2]/input</value>
      <webElementGuid>f66fc56c-c97c-4a79-bb12-e78ec756839b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>c3086e8a-8cc5-428a-a4ba-52cd57b3091b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'datepickerAddTemporaryPerTransactionStartDate' and @id = 'datepickerAddTemporaryPerTransactionStartDate']</value>
      <webElementGuid>c3e888b1-6065-4bed-bcd0-10c63df3b39c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
