<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Expire Date Temporary Per Month_datep_d5b0b0</name>
   <tag></tag>
   <elementGuidId>82ecb483-d03d-4b61-bd11-2aace3a3e09f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#datepickerAddTemporaryPerMonthExpireDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='datepickerAddTemporaryPerMonthExpireDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>98553bf5-315a-4d34-a3ff-3c6be1eb2b7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d46d216b-dc37-484d-b11f-5716b99b63de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>datepickerAddTemporaryPerMonthExpireDate</value>
      <webElementGuid>cc3a1406-1041-4a6d-af68-853f3bbfd502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>datepickerAddTemporaryPerMonthExpireDate</value>
      <webElementGuid>e6d1c4a2-c92c-43e9-b843-ee8f2782284b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filterDate white hasDatepicker</value>
      <webElementGuid>5a14b8c8-a902-4e76-a779-4b6aaecc0c13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>End date</value>
      <webElementGuid>0edba8d9-bc4b-4ffd-a4d9-ad9bd76dac11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d525f667-ff9f-459d-84d2-7d2f9cc017c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datepickerAddTemporaryPerMonthExpireDate&quot;)</value>
      <webElementGuid>5ceb216b-4704-494a-941c-7d17f3a94e65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='datepickerAddTemporaryPerMonthExpireDate']</value>
      <webElementGuid>fcb85128-7ce9-4047-b092-c9035c42274d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='temporaryPerMonth']/div[2]/input[2]</value>
      <webElementGuid>ed2e3328-a124-49c4-8570-1070c66e2e42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/input[2]</value>
      <webElementGuid>e789147b-2bf8-48be-98c8-6e33dc415752</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'datepickerAddTemporaryPerMonthExpireDate' and @id = 'datepickerAddTemporaryPerMonthExpireDate']</value>
      <webElementGuid>15722668-b06b-4289-aff0-19e38ff84c1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
