<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Please enter valid Temporary Start Date</name>
   <tag></tag>
   <elementGuidId>d395bf0b-1bfc-4dbf-93a5-1301f0739b80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#datepickerAddTemporaryPerTransactionStartDateError > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='datepickerAddTemporaryPerTransactionStartDateError']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>68b00781-4ab7-4bd2-80c4-6c0538525bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please enter valid Temporary Start Date</value>
      <webElementGuid>7291e3a2-e53c-4b9a-9f15-766fbe4bc9d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tempPerTranStartDateError&quot;)/span[1]</value>
      <webElementGuid>f52ebba4-62fb-4cbe-9574-b68087e5002b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>51cce0d4-261d-4200-82fb-9cfaf98c4c83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please enter valid Temporary Start Date</value>
      <webElementGuid>10bcc2b2-484b-40e1-b75b-addc6236a0ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tempPerTranStartDateError&quot;)/span[1]</value>
      <webElementGuid>fa37a27b-a397-440b-af72-5c9afbb907f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>780745e3-1927-4294-b15a-370a07ef7347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please enter valid Temporary Start Date</value>
      <webElementGuid>5e7daa33-2b1f-4e3d-8ae4-dda933eb18fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tempPerTranStartDateError&quot;)/span[1]</value>
      <webElementGuid>0b69beb9-5718-45e5-a326-500ba7aa3f4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cb148fc1-fc70-4b4e-87d9-e8c5b9b22b5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please enter valid Temporary Start Date</value>
      <webElementGuid>752552f7-af15-43d6-b6b3-2c9bfa1db984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tempPerTranStartDateError&quot;)/span[1]</value>
      <webElementGuid>39aabbcc-a51d-4c5a-830e-3ba4c307fe41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='datepickerAddTemporaryPerTransactionStartDateError']/span</value>
      <webElementGuid>a98f4e09-92bc-48ad-8a8c-0ebaa5900be5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Temporary Limit Per Transaction:'])[1]/following::span[2]</value>
      <webElementGuid>5989a935-7dba-4b19-94ec-de6247534052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter valid Temporary End Date'])[1]/preceding::span[1]</value>
      <webElementGuid>fbfa9aac-12bb-4ee3-844d-5831ec783424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Temporary Limit Per Month:'])[1]/preceding::span[2]</value>
      <webElementGuid>661b3217-c3df-4a06-872f-f9540f6c8022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Please enter valid Temporary Start Date']/parent::*</value>
      <webElementGuid>a5e22e74-3e6b-4185-9144-da5f70ec23fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[4]/div/span</value>
      <webElementGuid>cdffa027-b94b-43a2-96e2-e79e839e6303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Please enter valid Temporary Start Date' or . = 'Please enter valid Temporary Start Date')]</value>
      <webElementGuid>f25835a6-0c25-4999-bfa0-b9b046542f3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tempPerTranStartDateError']/span</value>
      <webElementGuid>ee1de558-0f48-4478-b14b-87db03bc7022</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
