<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__1</name>
   <tag></tag>
   <elementGuidId>c191a969-0c9a-4a12-b534-bc85a7a70ba8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tempPerTranError > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tempPerTranError']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ac4bef56-6906-49a4-87c4-d504269cc502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>วงเงินชั่วคราวต่อรายการต้องมากกว่าวงเงินถาวรต่อรายการ</value>
      <webElementGuid>ae5c0eff-05a8-4fb7-8312-350f3bedb533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tempPerTranError&quot;)/span[1]</value>
      <webElementGuid>ee172df0-de64-4a54-b2c5-034ddc80c8cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8088eb1b-c156-431b-bc0c-83d60592c4f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>วงเงินชั่วคราวต่อรายการต้องมากกว่าวงเงินถาวรต่อรายการ</value>
      <webElementGuid>5692c560-91cd-4fbc-b5d2-bd8fcd4f5126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tempPerTranError&quot;)/span[1]</value>
      <webElementGuid>52310fbf-7360-42e5-aa2c-4edf4964d512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>46a50b14-0944-4b34-b011-de2e4e3df9ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>วงเงินชั่วคราวต่อรายการต้องมากกว่าวงเงินถาวรต่อรายการ</value>
      <webElementGuid>6c020272-ea47-42b1-90b5-7e3533c0f2d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tempPerTranError&quot;)/span[1]</value>
      <webElementGuid>7fd1c26b-1b7d-41a3-b1f6-55b5d2211e0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1124160e-3614-4498-b238-7346b3c8fffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>วงเงินชั่วคราวต่อรายการต้องมากกว่าวงเงินถาวรต่อรายการ</value>
      <webElementGuid>ae2cfbf2-52d8-4e78-acd4-e9955c3fbf55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tempPerTranError&quot;)/span[1]</value>
      <webElementGuid>8f87c08b-31c0-4e97-bb74-2efd31565e92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d43b2584-4629-4638-b459-7602551d6a57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>วงเงินชั่วคราวต่อรายการต้องมากกว่าวงเงินถาวรต่อรายการ</value>
      <webElementGuid>6265d2ac-9d08-49ef-b700-eeeb060cd575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tempPerTranError&quot;)/span[1]</value>
      <webElementGuid>c76ac748-e533-40dd-bf68-2595619c0d8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tempPerTranError']/span</value>
      <webElementGuid>6239030e-b565-4959-9484-b44e3ab52394</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Temporary Limit Per Transaction:'])[1]/following::span[1]</value>
      <webElementGuid>c7c8d2e8-d5b8-4308-a2c2-311cd6bf8517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter valid Temporary Start Date'])[1]/preceding::span[1]</value>
      <webElementGuid>841b824a-b140-4fd2-b418-b0fd4a82d935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='วงเงินชั่วคราวต่อรายการต้องมากกว่าวงเงินถาวรต่อรายการ']/parent::*</value>
      <webElementGuid>81a7d503-240b-4b88-b55f-0c72648ab056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/div[2]/div/span</value>
      <webElementGuid>500fd73d-b2b4-432f-b47c-2ef63ca3b47a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'วงเงินชั่วคราวต่อรายการต้องมากกว่าวงเงินถาวรต่อรายการ' or . = 'วงเงินชั่วคราวต่อรายการต้องมากกว่าวงเงินถาวรต่อรายการ')]</value>
      <webElementGuid>3cae5e0b-1f7c-4abc-9f70-a7fc00f0e427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div[2]/div/span</value>
      <webElementGuid>9a054418-34d7-4a2a-b711-5ebf5c4b7837</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
