<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Please enter valid Temporary Start Date</name>
   <tag></tag>
   <elementGuidId>d395bf0b-1bfc-4dbf-93a5-1301f0739b80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tempPerTranStartDateError > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tempPerTranStartDateError']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d393c3e9-49f3-4f46-8701-2eaa4fbb1ea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please enter valid Temporary Start Date</value>
      <webElementGuid>fd0c2c59-3ebc-4ddb-9184-f436c919edfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tempPerTranStartDateError&quot;)/span[1]</value>
      <webElementGuid>e92a5023-1372-4471-960f-45c7a95a5dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>51cce0d4-261d-4200-82fb-9cfaf98c4c83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please enter valid Temporary Start Date</value>
      <webElementGuid>10bcc2b2-484b-40e1-b75b-addc6236a0ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tempPerTranStartDateError&quot;)/span[1]</value>
      <webElementGuid>fa37a27b-a397-440b-af72-5c9afbb907f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>780745e3-1927-4294-b15a-370a07ef7347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please enter valid Temporary Start Date</value>
      <webElementGuid>5e7daa33-2b1f-4e3d-8ae4-dda933eb18fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tempPerTranStartDateError&quot;)/span[1]</value>
      <webElementGuid>0b69beb9-5718-45e5-a326-500ba7aa3f4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cb148fc1-fc70-4b4e-87d9-e8c5b9b22b5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please enter valid Temporary Start Date</value>
      <webElementGuid>752552f7-af15-43d6-b6b3-2c9bfa1db984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tempPerTranStartDateError&quot;)/span[1]</value>
      <webElementGuid>39aabbcc-a51d-4c5a-830e-3ba4c307fe41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tempPerTranStartDateError']/span</value>
      <webElementGuid>42536d1a-8079-4251-a7f3-f4a365f15c70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Temporary Limit Per Transaction:'])[1]/following::span[2]</value>
      <webElementGuid>d65f7890-366d-462f-9d82-f9bd5987e5a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter valid Temporary End Date'])[1]/preceding::span[1]</value>
      <webElementGuid>c6f6da46-26bf-4c19-a218-5b6c6e2d70f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Temporary Limit Per Month:'])[1]/preceding::span[2]</value>
      <webElementGuid>26add98b-1e17-46ff-ab83-df64d384de33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Please enter valid Temporary Start Date']/parent::*</value>
      <webElementGuid>3f4addef-e05b-445d-afff-1a71113a8b9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[4]/div/span</value>
      <webElementGuid>158889c4-2d85-4482-9b52-ae0dd6c19e61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Please enter valid Temporary Start Date' or . = 'Please enter valid Temporary Start Date')]</value>
      <webElementGuid>161b206c-a3fb-426e-a134-697887f0cbb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
