<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>f15d4516-d337-4630-b703-5c740face8c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tempPerMonthError']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tempPerMonthError > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>456b6897-b43a-4214-922e-a0b6a01160dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>กรุณาใส่จำนวนเงินหรือย้อนกลับ</value>
      <webElementGuid>68701a04-86b2-4b92-96ed-42468cff9cf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tempPerMonthError&quot;)/span[1]</value>
      <webElementGuid>e56ea64e-0392-4e50-abb7-6c3e1f2be305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>933ae494-6429-46d0-b647-03b2aa9b9e82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>กรุณาใส่จำนวนเงินหรือย้อนกลับ</value>
      <webElementGuid>d132cadc-2100-49dc-a730-7043a931c81c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tempPerMonthError&quot;)/span[1]</value>
      <webElementGuid>2eb3b660-f126-4f7a-96ed-5d7c155ac9ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e558edcd-c8ab-411d-9952-30fc22d73d79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>กรุณาใส่จำนวนเงินหรือย้อนกลับ</value>
      <webElementGuid>f8b4709a-82c2-467b-b017-0eac4ae1e7cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tempPerMonthError&quot;)/span[1]</value>
      <webElementGuid>a3d6f8c9-40ce-445f-a330-62d2388d8393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6a574a82-90db-4df7-9bbf-fd74cefbea82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>กรุณาใส่จำนวนเงินหรือย้อนกลับ</value>
      <webElementGuid>b180da50-9ac0-42d0-9077-9c8db3a8e933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tempPerMonthError&quot;)/span[1]</value>
      <webElementGuid>caa5d974-c832-462e-ad85-30815ae105e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>05aa917e-553d-4cc6-8df4-b6eaf0a9762a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>กรุณาใส่จำนวนเงินหรือย้อนกลับ</value>
      <webElementGuid>3b0a2a9c-f522-44e8-96b8-620d9270a452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tempPerMonthError&quot;)/span[1]</value>
      <webElementGuid>79fdf3af-a096-4d60-8376-c389df8abe1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c4139748-dc2b-43f4-b30b-43c767a58aa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>กรุณาใส่จำนวนเงินหรือย้อนกลับ</value>
      <webElementGuid>c8a80f58-5565-4480-8ea3-9ded8f459a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tempPerMonthError&quot;)/span[1]</value>
      <webElementGuid>0c4ec291-e2c7-4e22-be62-cf17dfdbab7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9380d9c7-e409-46ce-8822-83318f406607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>กรุณาใส่จำนวนเงินหรือย้อนกลับ</value>
      <webElementGuid>b32e8e2c-8f34-4971-b0fa-84eb9b572ec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tempPerMonthError&quot;)/span[1]</value>
      <webElementGuid>71b00815-77fd-4df4-ba28-9df17d0324bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>861409a4-b44c-4ddc-872e-13513af916ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>กรุณาใส่จำนวนเงินหรือย้อนกลับ</value>
      <webElementGuid>5530ce62-ff54-40e7-aef1-9d377137e3d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tempPerMonthError&quot;)/span[1]</value>
      <webElementGuid>8e4796e8-ffcb-4c46-bdc0-8736754037a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ee4e8000-ad68-4074-ad36-8ad0da8122e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>กรุณาใส่จำนวนเงินหรือย้อนกลับ</value>
      <webElementGuid>b982be48-c73c-46b9-ba25-370c00bcf774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tempPerMonthError&quot;)/span[1]</value>
      <webElementGuid>62ea9cab-3145-4a09-92ec-8fbdd2ee0936</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tempPerMonthError']/span</value>
      <webElementGuid>b0a3d252-1b7b-4732-a1f1-b178aa383c2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Temporary Limit Per Month:'])[1]/following::span[1]</value>
      <webElementGuid>3bb9c6b3-05d6-4fac-9ae6-c5377dca4ae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expire Date Temporary Per Month:'])[1]/preceding::span[1]</value>
      <webElementGuid>184d4237-4d9c-4718-b230-b860a56b8a83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks'])[2]/preceding::span[3]</value>
      <webElementGuid>5eb679e9-b98e-4fcd-b28a-6c7552124fb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='กรุณาใส่จำนวนเงินหรือย้อนกลับ']/parent::*</value>
      <webElementGuid>461c330c-cb89-4a65-95d2-a3a9f209bfe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/span</value>
      <webElementGuid>c4289641-9d08-4905-a8ca-7aad37f0cef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'กรุณาใส่จำนวนเงินหรือย้อนกลับ' or . = 'กรุณาใส่จำนวนเงินหรือย้อนกลับ')]</value>
      <webElementGuid>f2931d76-ca03-49c5-af0f-e5c91436c674</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
