<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Amount per Month must more than Amount_46b8eb</name>
   <tag></tag>
   <elementGuidId>b75b072e-f5d6-47dd-9279-b3c8f5927ab5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tempEDCPerMonthError > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tempEDCPerMonthError']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a674c10c-3807-4a41-ac26-87af908401d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Amount per Month must more than Amount per Transaction</value>
      <webElementGuid>ee4887d7-9997-4a46-a692-1a039af5bf7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tempEDCPerMonthError&quot;)/span[1]</value>
      <webElementGuid>ef00a12f-92e9-4906-9c75-1f9f921736f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tempEDCPerMonthError']/span</value>
      <webElementGuid>7f9a91e5-a06d-4156-84ff-9396089aab2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Temporary Limit Per Month:'])[1]/following::span[1]</value>
      <webElementGuid>2c9850e8-3026-4fed-b1a4-fa1725aae665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expire Date Temporary Per Month:'])[1]/preceding::span[1]</value>
      <webElementGuid>e128e253-07c6-4842-9646-64de8dafdfda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please Enter Valid Temporary Start Date'])[1]/preceding::span[1]</value>
      <webElementGuid>00fdc36c-fbc3-47ce-9be8-fd62a9e77928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Amount per Month must more than Amount per Transaction']/parent::*</value>
      <webElementGuid>8a2df2f6-faaa-41ca-91ae-c64c6835e67d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/span</value>
      <webElementGuid>8b9fcf78-cc8e-4483-b35f-abf610aad8a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Amount per Month must more than Amount per Transaction' or . = 'Amount per Month must more than Amount per Transaction')]</value>
      <webElementGuid>97fc2c28-13ae-4457-b07b-0dcc9ef629e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
