<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_AllCompanies</name>
   <tag></tag>
   <elementGuidId>545bf262-ea05-439d-b6cd-d8e2b6edaa9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.selected > a > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='topNavi']/li[2]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a6b98195-7e2f-4a5e-ab7a-50cecf23f9bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AllCompanies</value>
      <webElementGuid>5ca42bf0-ba69-48cd-8bc6-456a7416f826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topNavi&quot;)/li[@class=&quot;selected&quot;]/a[1]/span[1]</value>
      <webElementGuid>a27d27e4-7e48-4017-964b-cb0ff9f382fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='topNavi']/li[2]/a/span</value>
      <webElementGuid>2e046c5e-59d0-41e1-b001-fa6c619e8332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::span[1]</value>
      <webElementGuid>f79d3e5c-2488-4b98-a251-81cde6baa5b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your last log in was Thursday, 20 Apr 2023 16:02'])[1]/following::span[2]</value>
      <webElementGuid>3cd9ba85-3b49-4f05-96a8-29d68ae2dafe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ControlLimit'])[1]/preceding::span[1]</value>
      <webElementGuid>beeda486-b40a-4d3d-ae2d-6f38322f2330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ManageStaffs'])[1]/preceding::span[2]</value>
      <webElementGuid>b58dcf74-a6ac-41d2-ab8d-ce26a932a185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='All']/parent::*</value>
      <webElementGuid>88822219-e626-4ce7-b423-11a7ab433dbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/span</value>
      <webElementGuid>62460981-6976-4353-a29c-823e6c05be5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'AllCompanies' or . = 'AllCompanies')]</value>
      <webElementGuid>1aa72edc-efc4-44be-aece-c5ffa7986cd1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
