<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View Details</name>
   <tag></tag>
   <elementGuidId>483e55a7-fb85-4067-8a65-494244e87c44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='detailBoxWhite']/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#detailBoxWhite > div.floatR > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>87b37e2f-9a48-4d8c-8775-452c52513331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/company/viewManageGroup?itemid=90253</value>
      <webElementGuid>99ce4de9-cd87-4472-ba8e-11267763ad9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Details</value>
      <webElementGuid>84c41a72-ab66-4e5b-b896-25a3d779a0e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;detailBoxWhite&quot;)/div[@class=&quot;floatR&quot;]/a[1]</value>
      <webElementGuid>81ea389f-012a-493b-a48d-b5c038d08cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1e60ee33-f058-48b0-a08b-40b61ab2b85c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/company/viewManageGroup?itemid=90253</value>
      <webElementGuid>ac5000cc-5e04-48af-bd79-f8db0c5fbe33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Details</value>
      <webElementGuid>0a46d206-e1c6-4c33-b69c-63adad0d2966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;detailBoxWhite&quot;)/div[@class=&quot;floatR&quot;]/a[1]</value>
      <webElementGuid>26d4c37a-0c95-4bb2-aaec-ff06a9fc0983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>00d61ef4-eb0c-4320-b041-bc0542b1a215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/company/viewManageGroup?itemid=90253</value>
      <webElementGuid>11552279-10db-413b-9e53-fcb531660d76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Details</value>
      <webElementGuid>8129c488-6ada-410b-a43c-b7b3b3f47fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;detailBoxWhite&quot;)/div[@class=&quot;floatR&quot;]/a[1]</value>
      <webElementGuid>49cfba62-3529-42d8-b1bb-a98d676d2b72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='detailBoxWhite']/div/a</value>
      <webElementGuid>15df7dff-7b21-4d73-8726-db6707b79081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View Details')]</value>
      <webElementGuid>4cf760c0-a4fb-47cc-b777-dcb64b6637c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registered TID/ Total TID'])[1]/following::a[1]</value>
      <webElementGuid>3cfc9aa0-25e2-48e4-9847-26e92cfcb5b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::a[1]</value>
      <webElementGuid>2eac4a83-3db3-4b3f-ae48-0ad0d267e69f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add MID'])[1]/preceding::a[1]</value>
      <webElementGuid>1b793146-fac1-4e69-adf8-1ae59bd6ef19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Full Payment'])[1]/preceding::a[2]</value>
      <webElementGuid>84331b67-b085-4bdd-9d43-381498842e75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View Details']/parent::*</value>
      <webElementGuid>52e4a145-0f1b-4229-bee8-645f677a7a93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/company/viewManageGroup?itemid=90253')]</value>
      <webElementGuid>e7f4b4d1-64c0-4daf-ae91-10f7e3888aa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div/a</value>
      <webElementGuid>27eb179a-d65d-487c-a0f8-22feefc89c28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/company/viewManageGroup?itemid=90253' and (text() = 'View Details' or . = 'View Details')]</value>
      <webElementGuid>2eb3851b-d148-4d66-8a2a-90719f49c1d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
