<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View Details</name>
   <tag></tag>
   <elementGuidId>483e55a7-fb85-4067-8a65-494244e87c44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='detailBoxWhite']/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#detailBoxWhite > div.floatR > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d929f84f-08d1-45d1-b4f3-e08d67179358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/controlLimit/viewManageGroupEDC?itemid=53433</value>
      <webElementGuid>716a8fbb-438b-4288-9169-8567fab8f34b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Details</value>
      <webElementGuid>19c79f37-c4d4-42a9-b353-e015ef07553e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;detailBoxWhite&quot;)/div[@class=&quot;floatR&quot;]/a[1]</value>
      <webElementGuid>cd63c414-d919-4b12-a1a6-506f12db8ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1e60ee33-f058-48b0-a08b-40b61ab2b85c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/company/viewManageGroup?itemid=90253</value>
      <webElementGuid>ac5000cc-5e04-48af-bd79-f8db0c5fbe33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Details</value>
      <webElementGuid>0a46d206-e1c6-4c33-b69c-63adad0d2966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;detailBoxWhite&quot;)/div[@class=&quot;floatR&quot;]/a[1]</value>
      <webElementGuid>26d4c37a-0c95-4bb2-aaec-ff06a9fc0983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>00d61ef4-eb0c-4320-b041-bc0542b1a215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/company/viewManageGroup?itemid=90253</value>
      <webElementGuid>11552279-10db-413b-9e53-fcb531660d76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Details</value>
      <webElementGuid>8129c488-6ada-410b-a43c-b7b3b3f47fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;detailBoxWhite&quot;)/div[@class=&quot;floatR&quot;]/a[1]</value>
      <webElementGuid>49cfba62-3529-42d8-b1bb-a98d676d2b72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='detailBoxWhite']/div/a</value>
      <webElementGuid>de034ca2-90c3-489c-b2ff-acc242f05f1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View Details')]</value>
      <webElementGuid>6b76ad64-d8ad-47bd-b366-ef4825c24a7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registered TID/ Total TID'])[1]/following::a[1]</value>
      <webElementGuid>76e1b5cb-7e8c-4559-9012-2190a0cbeb60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::a[1]</value>
      <webElementGuid>272ae1cb-06af-46d5-8b63-fd14b6643b6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add MID'])[1]/preceding::a[1]</value>
      <webElementGuid>7784632f-0553-454a-b840-55f41ae65d70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EDC'])[1]/preceding::a[2]</value>
      <webElementGuid>0a85f216-d070-4651-9491-f488b8a4e109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View Details']/parent::*</value>
      <webElementGuid>6a2b31f6-8189-404e-b181-9df0b220e866</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/controlLimit/viewManageGroupEDC?itemid=53433')]</value>
      <webElementGuid>f24004ae-50cb-4e9b-a540-c283e5636c19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/a</value>
      <webElementGuid>718cd4ec-d9e5-4b49-9b32-ae76e827fa7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/controlLimit/viewManageGroupEDC?itemid=53433' and (text() = 'View Details' or . = 'View Details')]</value>
      <webElementGuid>51ad5add-99c5-4d7b-b372-e93b867bfb2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Full Payment'])[1]/preceding::a[2]</value>
      <webElementGuid>84331b67-b085-4bdd-9d43-381498842e75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/company/viewManageGroup?itemid=90253')]</value>
      <webElementGuid>e7f4b4d1-64c0-4daf-ae91-10f7e3888aa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div/a</value>
      <webElementGuid>27eb179a-d65d-487c-a0f8-22feefc89c28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/company/viewManageGroup?itemid=90253' and (text() = 'View Details' or . = 'View Details')]</value>
      <webElementGuid>2eb3851b-d148-4d66-8a2a-90719f49c1d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
