<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_74734538</name>
   <tag></tag>
   <elementGuidId>5851e488-f1c5-465c-9172-1effb33d4a2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='start']/div/span/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.wrapped120</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3a9bd567-48d4-42b6-833d-a582a59d4371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wrapped120</value>
      <webElementGuid>61b5dba3-b492-4ffe-9b7e-59b8f70933fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>74734538</value>
      <webElementGuid>55c4a6ee-689a-4133-b8c4-7103eb865e2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dataRow&quot;)/tbody[1]/tr[@class=&quot;dataListMid&quot;]/td[@id=&quot;start&quot;]/div[1]/span[1]/div[@class=&quot;wrapped120&quot;]</value>
      <webElementGuid>d536e5dd-8277-4aff-824e-17ba5d5f62af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='start']/div/span/div</value>
      <webElementGuid>fce03b60-58c6-459a-9287-5b14a4cb623e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company Name'])[1]/following::div[2]</value>
      <webElementGuid>5f808bce-818a-4712-918e-3dbd2471e93b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created Date'])[1]/following::div[2]</value>
      <webElementGuid>39867296-81a9-418a-9a52-cb732bb5a534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='pun2811111111'])[1]/preceding::div[1]</value>
      <webElementGuid>3fe05bbc-4e66-4263-ad8e-8736bcb7860d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='74734538']/parent::*</value>
      <webElementGuid>ed5dfccf-b3e9-4fcd-a026-060f1554f3e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div</value>
      <webElementGuid>ab9f4870-3e08-46ee-91c7-d610c835e1d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '74734538' or . = '74734538')]</value>
      <webElementGuid>7c7c8257-e37b-4f91-966a-5d76bed588cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
