<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Continue (1)</name>
   <tag></tag>
   <elementGuidId>3b741c2f-02e8-4e57-a828-decb0caf33db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='popupAutoResize']/div[4]/form/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fe210201-8f03-4c23-8852-530207d9aad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button btnL</value>
      <webElementGuid>bccfcaad-f77e-4ea9-88f7-4c285896d762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:document.doDelinkForm.submit();</value>
      <webElementGuid>ecac32dc-7d98-49e7-aaf5-8ed34b66da18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>e47b1e06-3cee-40e8-b28a-41a00742757c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popupAutoResize&quot;)/div[@class=&quot;popupButton&quot;]/form[1]/a[@class=&quot;button btnL&quot;]</value>
      <webElementGuid>90263cf5-500a-4428-8d6f-b8c1d86ec7aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Reader DetailsKasikornbank/iframe_concat(id(, , fancybox-frame16849198_4d8f5e</value>
      <webElementGuid>1ca83ac6-2468-4fe1-8c47-6588989e8d51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popupAutoResize']/div[4]/form/a[2]</value>
      <webElementGuid>7a5a3a41-c990-41c8-bcef-48509b2240ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Continue')]</value>
      <webElementGuid>0929f177-9834-4d32-a23a-7b8eeeb8ae80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::a[1]</value>
      <webElementGuid>f37f4d50-432b-4075-be81-0f1798d714f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue']/parent::*</value>
      <webElementGuid>2291c100-d1a5-4ad2-aa0d-f1c8e648f5b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:document.doDelinkForm.submit();')]</value>
      <webElementGuid>60a5223a-2885-49cc-8baf-bfd63bcfdc1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>51783d9d-5548-479b-8442-12488f5dd081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:document.doDelinkForm.submit();' and (text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>ba231064-0163-4f92-a0e6-5987fbad7e3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
