<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , fancybox-frame16849198_0f5fd3</name>
   <tag></tag>
   <elementGuidId>399a0cf4-59be-4fac-b274-3bad7de5e42b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fancybox-frame1684919859195</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='fancybox-frame1684919859195']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>54c257c9-ae7a-4f76-a1de-59464abd6fad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fancybox-frame1684919859195</value>
      <webElementGuid>98b29722-5720-430b-82ca-2cfb45f94470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fancybox-frame1684919859195</value>
      <webElementGuid>8b8a3841-5ab7-4537-9a14-ad9fa42faa5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fancybox-iframe</value>
      <webElementGuid>64698c78-4eda-411c-9ca7-3296b4770824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>97186571-b035-4eeb-b19b-43d346cdd43b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>vspace</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>029e65b3-855d-4b54-8a75-095bc532d083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hspace</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b13830ab-37d5-4566-8479-7dfbf7af6a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>3682972c-2f8c-433b-b698-59dfabb6db56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>reInjection?itemid=123293</value>
      <webElementGuid>335ff894-0ec8-4e23-89dc-852077f7899e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fancybox-frame1684919859195&quot;)</value>
      <webElementGuid>521797ec-d045-4947-9a5e-f215acce25db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='fancybox-frame1684919859195']</value>
      <webElementGuid>1c45faeb-0f89-43dd-9e55-3816843a5d19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>68763e83-a862-4d58-93fd-1f49a075a931</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'fancybox-frame1684919859195' and @name = 'fancybox-frame1684919859195' and @src = 'reInjection?itemid=123293']</value>
      <webElementGuid>2d150ac7-7e68-4f92-8628-b1e4a44bb5fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
