<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , fancybox-frame16849198_4d8f5e</name>
   <tag></tag>
   <elementGuidId>ad746ef9-5240-4927-a75c-9884da7df398</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fancybox-frame1684919877288</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='fancybox-frame1684919877288']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>63967191-d95f-4063-98ca-eb57086deed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fancybox-frame1684919877288</value>
      <webElementGuid>c25d49d1-5738-4829-86db-5114d7d5543e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fancybox-frame1684919877288</value>
      <webElementGuid>ba1ff209-6334-43ff-8b6e-5756e6f56eb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fancybox-iframe</value>
      <webElementGuid>3d684d4b-e2e8-4daa-b19a-e3499b5550a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>63fa8ac2-0280-4a89-8398-002b663129f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>vspace</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5d8f3600-2440-448b-a68b-ce7d442f3122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hspace</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3ef5f2c8-3454-49c1-ae45-db0a608b3af5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>26759171-9110-4f25-be81-251e5c817b59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>delink?itemid=123293</value>
      <webElementGuid>4a8fa7df-3537-4cb3-a5fa-a0305fd7417a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fancybox-frame1684919877288&quot;)</value>
      <webElementGuid>f2c21923-a8df-4763-b717-a8926cf0c956</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='fancybox-frame1684919877288']</value>
      <webElementGuid>dec3cb45-64d7-4ab0-92ea-c4cb7ddf5956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>3acd31e8-3ffb-4360-b96e-990570b4d130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'fancybox-frame1684919877288' and @name = 'fancybox-frame1684919877288' and @src = 'delink?itemid=123293']</value>
      <webElementGuid>917ad6ab-beb8-4715-8728-f01ac06fcbf2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
