<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Go</name>
   <tag></tag>
   <elementGuidId>28ac2c5d-aeee-4984-a6dd-9abeab145ad4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='buttonGo'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#go149462 > div.floatL > #buttonGo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>429b5457-48fe-4800-956d-657b2a7f5b90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buttonGo</value>
      <webElementGuid>62d4876b-8d65-430d-a2a0-26d6f0975709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font13Bold</value>
      <webElementGuid>1c5ac3d9-e506-4ef1-a59d-9f378091c7b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:document.go149462.submit();</value>
      <webElementGuid>61266e99-f0e5-4d7a-b773-7a6adba1d288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
				                		Go
				                	</value>
      <webElementGuid>0a0a3686-ce5e-4e58-ab5c-004205bcea66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;go149462&quot;)/div[@class=&quot;floatL&quot;]/a[@id=&quot;buttonGo&quot;]</value>
      <webElementGuid>b09545cf-f6a5-4a25-9a52-01dec39bdfdd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id='buttonGo'])[2]</value>
      <webElementGuid>7ee65c94-11f3-4ad4-96b4-11451cf34d26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='go149462']/div[2]/a</value>
      <webElementGuid>79914458-f9a1-420c-8d9d-46607a561ddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Go')])[2]</value>
      <webElementGuid>aa3eea26-8845-4152-9b85-2a1ea33c0f4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Details'])[3]/following::a[1]</value>
      <webElementGuid>b3f00d57-6f2d-4f52-956e-a93ccca7562f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Digio'])[3]/preceding::a[1]</value>
      <webElementGuid>8501ab35-0c7b-494a-ad7b-3ebfdd28e0fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='testaddee'])[1]/preceding::a[1]</value>
      <webElementGuid>20d7aed4-9dd0-49f2-89b9-99d9c09e9d7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:document.go149462.submit();')]</value>
      <webElementGuid>58a3d609-cab4-40cd-ae31-e842d330845c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[6]/form/div[2]/a</value>
      <webElementGuid>d63796de-610f-4398-ac05-4e1171fa78f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'buttonGo' and @href = 'javascript:document.go149462.submit();' and (text() = '
				                		Go
				                	' or . = '
				                		Go
				                	')]</value>
      <webElementGuid>ecd01178-b83a-4ede-acb0-7a04c1a4f04d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
