<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_PrevNextJanFebMarAprMayJunJulAugSepOctN_452e49</name>
   <tag></tag>
   <elementGuidId>653db2a0-361b-451b-be47-57633b181545</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ui-datepicker-header.ui-widget-header.ui-helper-clearfix.ui-corner-all</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-datepicker-div']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>70e11ee7-fb06-4635-b7de-2f9230f651c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-datepicker-header ui-widget-header ui-helper-clearfix ui-corner-all</value>
      <webElementGuid>c0061ad4-b648-4c7d-b005-6abc6150a985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PrevNextJanFebMarAprMayJunJulAugSepOctNovDec2011201220132014201520162017201820192020202120222023</value>
      <webElementGuid>3c6140ab-73fa-475b-9b78-2b46906a330d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-datepicker-div&quot;)/div[@class=&quot;ui-datepicker-header ui-widget-header ui-helper-clearfix ui-corner-all&quot;]</value>
      <webElementGuid>9b1f2a16-a820-48ef-b3f8-fa2c5d9971d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-datepicker-div']/div</value>
      <webElementGuid>003f62d1-3dad-45d7-b85c-b03369a5f5ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes, keep me signed in'])[1]/following::div[2]</value>
      <webElementGuid>28ba1a0a-d5cb-42e9-97f5-acfdf802adbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No, sign me out'])[1]/following::div[2]</value>
      <webElementGuid>c46364be-8089-4f52-b7c2-c6534b72f390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div</value>
      <webElementGuid>e236dc92-5254-4a17-9009-47660cd0762a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'PrevNextJanFebMarAprMayJunJulAugSepOctNovDec2011201220132014201520162017201820192020202120222023' or . = 'PrevNextJanFebMarAprMayJunJulAugSepOctNovDec2011201220132014201520162017201820192020202120222023')]</value>
      <webElementGuid>c5188b67-bbcd-4340-b4b4-e031c2ff8dfc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
