<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_JanFebMarAprMayJun</name>
   <tag></tag>
   <elementGuidId>26716858-39ca-43d3-96a8-610846c21b6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select.ui-datepicker-month</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@onclick=&quot;DP_jQuery_1686299381833.datepicker._clickMonthYear('#fromdate');&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>97423ce5-7c5c-4029-9db2-ab90977c8359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-datepicker-month</value>
      <webElementGuid>8bd68fd7-33bb-4e88-abcd-f84a40981f59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>DP_jQuery_1686299381833.datepicker._selectMonthYear('#fromdate', this, 'M');</value>
      <webElementGuid>cebc77bc-c9a0-4699-afac-554b75ce2b46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>DP_jQuery_1686299381833.datepicker._clickMonthYear('#fromdate');</value>
      <webElementGuid>63316d2a-250d-4a49-8bf6-101405c43aa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>831ada41-359e-47eb-8749-b6b61b11a959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JanFebMarAprMayJun</value>
      <webElementGuid>eab67fa6-b25e-464e-a9cd-68f39a573886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-datepicker-div&quot;)/div[@class=&quot;ui-datepicker-header ui-widget-header ui-helper-clearfix ui-corner-all&quot;]/div[@class=&quot;ui-datepicker-title&quot;]/select[@class=&quot;ui-datepicker-month&quot;]</value>
      <webElementGuid>ed40b9fc-d5c3-45fb-8b42-76eeeb808f82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@onclick=&quot;DP_jQuery_1686299381833.datepicker._clickMonthYear('#fromdate');&quot;]</value>
      <webElementGuid>2fd6f35a-ecd3-479a-85b9-62724bd34752</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-datepicker-div']/div/div/select</value>
      <webElementGuid>ed7b44aa-06eb-4edf-93b2-bb9b1ac835e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::select[1]</value>
      <webElementGuid>5906b257-5be1-4e03-9ae5-c284a2718d38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prev'])[1]/following::select[1]</value>
      <webElementGuid>c38fde03-1c29-46f5-b9f8-3a8290df5022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Su'])[1]/preceding::select[2]</value>
      <webElementGuid>878e640a-f966-46f8-b762-6a62a46e1194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mo'])[1]/preceding::select[2]</value>
      <webElementGuid>1f1c430e-37b8-4084-8eb4-a1cac13fb325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/select</value>
      <webElementGuid>84ea2b39-49d9-4833-bbfd-60604bccb8a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = 'JanFebMarAprMayJun' or . = 'JanFebMarAprMayJun')]</value>
      <webElementGuid>075f50de-f47d-4feb-8cf7-60752ed9d306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@onclick=&quot;DP_jQuery_1686125635979.datepicker._clickMonthYear('#fromdate');&quot;]</value>
      <webElementGuid>6becffa9-f3ba-4917-b696-19823d964e9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
